{
  "hash": "f776e2ed47e108f7f37d0cba12314f2f",
  "result": {
    "engine": "knitr",
    "markdown": "# Regresjon: Sammenheng mellom variable\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(gtsummary)\nlibrary(modelsummary)\n```\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\n\n\nVi skal her se på helt grunnleggende lineær regresjon med en og to forklaringsvariable.\n\n## Scatterplot\n\nBivariat regresjon beskriver sammenhengen mellom to variable. En naturlig start er å se på et scatterplot. Her er en figur som viser hvordan timelønn varierer med alder. I det nedenforstående er det brukt jitter og gjennomsiktig farge for å håndtere overplotting.\n\nI tillegg er det tegnet inn en linje som illustrerer *trenden i gjennomsnittlig lønn* med alder. Denne linjen skrår svakt oppover, som altså betyr at gjennomsnittlig lønn øker noe med alder. Vi ser med det blotte øyet at en rett linje ikke beskriver denne sammenhengen perfekt. Først og fremst er det en stor variasjon rundt denne linjen, så det er mye annet som påvirker lønna enn alder. Det er også verd å legge merke til at i de yngste aldersgruppene er lønna en god del lavere - og kanskje litt lavere i eldste aldersgrupper også. Så en rett linje er kanskje ikke optimalt i utgangspunktet. Fordelen med en rett linje er at vi kan si noe slikt som at \"gjennosmsnittslønna øker med x antall kroner for hvert år eldre man blir\". Hvis linja er kurvlineær blir det litt mer komplisert. Så et første poeng er at en slik linje er en *forenkling*, og det er en tilsiktet forenkling.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(abu89, aes(x =age, y = time89))+\n  geom_jitter(alpha = .2)+\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output-display}\n![](lineaer_regresjon_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\nDet er en viss tendens til at lønnen øker med alder, men det er ikke helt lett å si hvor mye. Poenget med lineær regresjon er å beskrive en gjennomsnittlig trend.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(abu89, aes(x =age, y = time89))+\n  geom_jitter(alpha = .2)+\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output-display}\n![](lineaer_regresjon_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\nDenne trendlinja er hva vi vanligvis kaller regresjonslinje.\n\n## Regresjonslinja\n\nRegresjonslinja kan beskrives med et *stigningstall*, som sier hvor bratt linjen er. Substansielt sett betyr det hvor mye utfallsvariabelen (y-aksen) endres med økning i forklaringsvariabelen (x-aksen). I tillegg trenger vi også vite hvor høyt/lavt linjen ligger.[^linearregresjon-1] Til det bruker vi startpunktet for linjen, der hvor $x$ har verdien 0. Dette må regnes ut, og det er akkurat dette estimering av lineær regresjon gir oss.\n\n[^linearregresjon-1]: Du kan jo tenke deg flere parallelle linjer i plottet ovenfor med samme stigningstall\n\nUtregningen av regresjonslinja går vi ikke inn på her, men intuitivt sett ønsker vi jo *den beste linja* og ikke en hvilken som helst omtrentlig linje. Datapunktene (de svarte punktene i grafen) er spredt rundt linja, og avstanden mellom linje og punkt kalles *residualer*. Summen av disse residualene er grunnlaget for mål på hvor godt regresjonslinja beskriver de faktiske dataene. Den beste linja er definert som den som minimerer residualene. Det er dette som kalles \"minste kvadraters metode\".\n\nI R estimeres regresjonsmodeller med funksjonen `lm`. Første argument er en formel på formen `utfallsvariabel ~ forklaringsvariabel`. Rekkefølgen variablene oppgis i er altså viktig. Dernest må det spesifiseres hvilket datasett som skal brukes med `data = ` .[^linearregresjon-2]\n\n[^linearregresjon-2]: Grunnen til det siste er at R kan ha flere datasett oppe samtidig, så R vet ikke nødvendigvis hvilket datasett du tenker på\n\nLegg alltid resultatene i et eget objekt med et navnt som er rimelig enkelt å forstå hva er. I følgende kode legges resultatet i en nytt objekt `lm_est1`. Deretter bruker kan man hente ut de delene av resultatet vi er interessert i. I aller første omgang er bare interessert i regresjonslinjas konstantledd (startpunktet) og stigningstall. Disse kaller vi vanligvis *regresjonskoeffisienter*. Det kan vi få ut ved å bruke funksjonen `coef`. (Vi kommer tilbake til å se på de fulle resultatene senere, som vi oftest er interessert i).\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_est1 <- lm(time89 ~ age, data = abu89)\ncoef(lm_est1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)         age \n 71.1101883   0.4828415 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nRegresjonslingningen kan skrives på formel der $\\alpha$ er konstantleddet og $\\beta$ er stigningstallet slik:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\n\n$$\n\\operatorname{time89} = \\alpha + \\beta_{1}(\\operatorname{age}) + \\epsilon\n$$\n\nNår vi setter inn de estimerte koeffisientene inn i ligningen får vi følgende:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\n\n\n$$\n\\operatorname{\\widehat{time89}} = 71.11 + 0.48(\\operatorname{age})\n$$\n\nTolkningen her er at gjennomsnittlig forskjell i timelønn mellom grupper der aldersforskjellen er ett år er 0.48 kroner i favør av den eldre gruppen.[^linearregresjon-3] Merk enheten her: stigningstallet tolkes på den skalaen utfallsvariabelen er på, i dette tilfellet kroner. Det er også uttrykt endring ved at forklaringsvariabelen endres med nøyaktig 1.\n\n[^linearregresjon-3]: Noen ganger sier man at gjennomsnittslønna øker med 0.48 kroner for hvert år eldre man blir. Men det er ikke helt riktig, for dataene beskriver jo ikke individuell endringer over tid! Men hvis du synes det er lettere å tenke på det på den måten er det ok - men prøv å husk at det også er litt feil.\n\nVi sier gjerne at regresjonslinjen er *estimert*, og det innebærer at det er usikkerhet i estimatene. Vi kommer tilbake til dette, men en vanligere output fra regresjonsmodeller er å bruke funksjonen `summary`. Da får man med mye mer detaljer og output vil se ut som følger:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm_est1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = time89 ~ age, data = abu89)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-69.287 -19.131  -6.304  12.864 255.258 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 71.11019    1.62232   43.83   <2e-16 ***\nage          0.48284    0.03926   12.30   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 29.73 on 3757 degrees of freedom\n  (368 observations deleted due to missingness)\nMultiple R-squared:  0.0387,\tAdjusted R-squared:  0.03844 \nF-statistic: 151.2 on 1 and 3757 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n## Dummy-variable \nHvis en forklaringsvariabel har kun to verdier vil vi typisk gi den ene kategorien verdien 0 og den andre kategorien 1. Dette kalles en «dummy variabel» eller en «indikator variabel». For eksempel vil et datasett ofte ha en variabel for kjønn med verdiene «Mann» og «Kvinne». Da kan vi la mann få verdien 0 og kvinne verdien 1. Ofte vil man da gi variabelen et navn som indikerer hvilken verdi som er 1. Så i dette eksempelet er det hensiktsmessig å gi den nye variabelen navnet «Kvinne». I dette eksempelet vil man også kunne si at variabelen er en «dummy for kvinne» (altså: den kategorien som får verdien 1).\n\nDet spiller ingen rolle hvilken kategori som får verdien 0 og 1. I dette eksempelet kunne man like gjerne gjort det motsatt, og latt det være en «dummy for mann». Da ville det være naturlig å kalle variabelen «mann» i stedet for «kvinne». Som vi skal se nedenfor vil det bare påvirke fortegnet når vi bruker variabelen i en regresjonsanalyse.\n\nI datasettet abu89 er variabelen \"female\" en slik variabel som har verdiene 0 eller 1, og der 0 betyr \"mann\" og 1 betyr \"kvinne\".\n\n| Kjønn  | Female |\n|--------|--------|\n| Mann   | 0      |\n| Kvinne | 1      |\n| Kvinne | 1      |\n| Mann   | 0      |\n| Kvinne | 1      |\n| Kvinne | 1      |\n| Kvinne | 1      |\n| Mann   | 0      |\n\n\nI R vil vi ofte ha slike variable som factor-variable. Da er variabelen definert som kategorisk og selv om det er tekst-verdier i variabelen, så vil R automatisk behandle den som om verdiene var 0 og 1 i estimeringen av regresjonsmodellen. \n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheme_gtsummary_mean_sd()\nabu89 %>% \n  select(female, time89) %>% \n  tbl_summary(by = female) \n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"gkqocsdlmf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gkqocsdlmf table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gkqocsdlmf thead, #gkqocsdlmf tbody, #gkqocsdlmf tfoot, #gkqocsdlmf tr, #gkqocsdlmf td, #gkqocsdlmf th {\n  border-style: none;\n}\n\n#gkqocsdlmf p {\n  margin: 0;\n  padding: 0;\n}\n\n#gkqocsdlmf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gkqocsdlmf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gkqocsdlmf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gkqocsdlmf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gkqocsdlmf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gkqocsdlmf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gkqocsdlmf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gkqocsdlmf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gkqocsdlmf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gkqocsdlmf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gkqocsdlmf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gkqocsdlmf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gkqocsdlmf .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gkqocsdlmf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gkqocsdlmf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gkqocsdlmf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gkqocsdlmf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gkqocsdlmf .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gkqocsdlmf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gkqocsdlmf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gkqocsdlmf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gkqocsdlmf .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gkqocsdlmf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gkqocsdlmf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gkqocsdlmf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gkqocsdlmf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gkqocsdlmf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gkqocsdlmf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gkqocsdlmf .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gkqocsdlmf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gkqocsdlmf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gkqocsdlmf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gkqocsdlmf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gkqocsdlmf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gkqocsdlmf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gkqocsdlmf .gt_left {\n  text-align: left;\n}\n\n#gkqocsdlmf .gt_center {\n  text-align: center;\n}\n\n#gkqocsdlmf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gkqocsdlmf .gt_font_normal {\n  font-weight: normal;\n}\n\n#gkqocsdlmf .gt_font_bold {\n  font-weight: bold;\n}\n\n#gkqocsdlmf .gt_font_italic {\n  font-style: italic;\n}\n\n#gkqocsdlmf .gt_super {\n  font-size: 65%;\n}\n\n#gkqocsdlmf .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gkqocsdlmf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gkqocsdlmf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gkqocsdlmf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gkqocsdlmf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gkqocsdlmf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gkqocsdlmf .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#gkqocsdlmf .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#gkqocsdlmf div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"KiowKiogIApOID0gMiwxOTM=\"><span class='gt_from_md'><strong>0</strong><br />\nN = 2,193</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"KioxKiogIApOID0gMSw5MzQ=\"><span class='gt_from_md'><strong>1</strong><br />\nN = 1,934</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Gjennomsnittlig timelønn 1989</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">100 (32)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">79 (24)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">190</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">178</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"3\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"TWVhbiAoU0Qp\"><span class='gt_from_md'>Mean (SD)</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n\n\n\nVi ser altså at menn hadde i gjennomsnitt høyere timelønn enn kvinner, nærmere bestemt 21 kroner mer. Dette kan vi også undersøke med lineær regresjon som følger:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_est_i <- lm(time89 ~ female , data = abu89)\n\ncoef(lm_est_i)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      female \n   99.84382   -20.75229 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\nRegresjonskoeffisenten for variabelen female uttrykker nettopp differansen mellom menn og kvinner, som er 21 kroner. Husk at $\\beta$ er hvor mye $y$-variabelen endres når man sammenligner $x$-variabelen med akkurat 1 enhets forskjell. Her er mann 0 og kvinner 1, så da er dette faktisk 1 enhets forskjell. Altså: når $x$ går fra 0 til 1, så reduseres $y$ med 21. Derfor negativt fortegn.  \n\nI R vil vi ofte gjøre om kategoriske variable til såkalte factor-variable. En factor-variabel vil håndtere kategoriske variable som tekst, men med en underliggende numerisk verdi. Da kan man bruke factor-variable i alle standard analysemetoder. I regresjon vil R automatisk bruke den første kategorien som referansekategori. \n\nVi kan gjøre den samme analysen med kjønn som en factor variabel og få de samme resultatene som ovenefor. \n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nabu89 <- abu89 %>%\n  mutate(sex = factor(ifelse(female == 1, \"Female\", \"Male\"), levels = c(\"Male\", \"Female\"))) %>% \n  filter(!is.na(time89))\n\nlm_est2 <- lm(time89 ~ female , data = abu89)\n\ncoef(lm_est2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      female \n   99.84382   -20.75229 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n### Dummy-variable med mer enn en kategori\nNoen ganger har vi forklaringsvariable med flere enn to kategorier. Det kan vi løse på en tilsvarende måte ved å lage flere dummy-variable. Et eksempel kan være sosial klasse. I datasettet abu89 er det fem kategorier. \n\nEn dummy-variabel har bare to kategorier: 0 og 1, men vi kan lage flere dummy-variable. Vi kan lager en ny variabel «klasse II» som har verdien 1 hvis personen tilhører denne klassen og 0 ellers. Altså en dummy. Så kan vi lage en ny variabel «Klasse III» som har verdien 1 hvis personen tilhører denne klassen og 0 ellers. Slik kan man lage en dummy-variabel for hver av kategoriene. Da har vi altså flere dummy-variable som til sammen fanger opp informasjonen i den opprinnelige variabelen.\n\n| Utdanning   | Klasse II | Klasse III | Klasse V-VI | Klasse VII |\n|-------------|-----------|------------|-------------|------------|\n| Klasse I    | 0         | 0          | 0           | 0          |\n| Klasse II   | 1         | 0          | 0           | 0          |\n| Klasse III  | 0         | 1          | 0           | 0          |\n| Klasse V-VI | 0         | 0          | 1           | 0          |\n| Klasse VII  | 0         | 0          | 0           | 1          |\n\nMerk at her er det ingen dummy for \"Klasse I\". Denne gruppen brukes som referansekategori slik at estimatene for *de andre* dummyene blir tolkbare som forskjellen til denne referansekategorien. Mer om det siden, men man kan velge å bruke en annen referansekategori hvis man vil.  \n\n\nLa oss først se på et plot. Her er det brukt en jitter-plot. Den røde linjen viser endring i gjennomsnitt mellom de kategoriene. En regresjonsanalyse vil gi slike estimater på differanser, men det er enklest hvis alle endringene er i forhold til samme referansekategori. \n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot( abu89x, aes(x =klasse89, y = time89))+\n  geom_jitter(alpha = .3, width = .2)+\n  geom_point(aes(y=gr_snitt), col = \"red\", size = 3)+\n  #geom_hline(yintercept = mean(abu89x$time89, na.rm = TRUE))+\n  geom_line(aes(x = as.numeric(klasse89), y = smooth), col = \"red\", linewidth = 1) \n```\n\n::: {.cell-output-display}\n![](lineaer_regresjon_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\n\n\nDen generelle regresjonsligningen skrives som $y=a+bx$, der $x$ er forklaringsvariabelen. Regresjonskoeffisienten, $b$, tolkes som hvor forskjellen i gjennomsnittet på utfallsvariabelen, $y$, mellom de som er en enhets forskjell på $x$-variabelen. \n\nSå kan vi kjøre en regresjon og få ut regresjonskoeffisientene på samme måte som før. Akkurat her er `coef` lagt inn i en parentes for `data.frame`, men det er bare for at det skal bli en pen kolonne. Vi kommer altså tilbake til teknikker for penere output nedenfor. \n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nest2 <- lm(time89 ~ klasse89, data = abu89)  \ndata.frame(coef(est2)) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                 coef.est2.\n(Intercept)                       118.39851\nklasse89II Nedre serviceklasse    -14.49078\nklasse89III Rutinefunksjonærer    -42.89842\nklasse89V-VI Faglærte arbeidere   -29.68788\nklasse89VIIa Ufaglærte arbeidere  -36.95234\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nHvert estimat for kategori for klasse sammenlignes med *den første kategorien* (altså den som mangler): klasse I. Det betyr at klasse VII (ufaglærte arbeidere) har en timelønn på -37 kroner mindre enn klasse I (øvre serviceklasse). Mens klasse II (nedre serviceklasse) tjener -14.5  kroner mindre enn klasse I.  \n\nForskjellen mellom andre grupper er således differansen mellom disse estimatene. Altså: klasse VII tjener mindre enn klasse V-VI: $36.9 - 29.7 = 7.2$ kroner. Se på plottet over, så ser du at disse tallene ser riktige ut. \n\n\n\n\n\n\n## Flere variable\nDet er ikke så ofte vi bruker regresjon med bare en forklaringsvariabel, såklat \"enkel lineær regresjon\".[^linearregresjon-4] Langt mer vanlig er å bruke flere variable samtidig i det vi kaller \"multippel regresjon\".[^linearregresjon-5] I multippel regresjon kan man altså beskrive mer kompliserte mønstre i dataene.\n\n[^linearregresjon-4]: Det er selvsagt ingenting *enkelt* med slike modeller utover at det finnes mer kompliserte varianter.\n\n[^linearregresjon-5]: Noen kaller dette også for *multivariat* regresjon, men det er tvetydig da det også kan bety modeller med flere utfallsvariable, som er noe ganske annet.\n\nVi fortsetter med eksempelet om lønn og alder, men utvider med en dimensjon til, nemlig kjønn. La oss først se på kjønnsforskjellene i gjennomsnittlig timelønn.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nabu89 <- abu89 %>%\n  mutate(sex = factor(ifelse(female == 1, \"Female\", \"Male\"), levels = c(\"Male\", \"Female\"))) %>% \n  filter(!is.na(time89))\n\nabu89 %>% \n  select(sex, time89) %>% \n  tbl_summary(by = sex) \n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"mjbsqcuvyr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mjbsqcuvyr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mjbsqcuvyr thead, #mjbsqcuvyr tbody, #mjbsqcuvyr tfoot, #mjbsqcuvyr tr, #mjbsqcuvyr td, #mjbsqcuvyr th {\n  border-style: none;\n}\n\n#mjbsqcuvyr p {\n  margin: 0;\n  padding: 0;\n}\n\n#mjbsqcuvyr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mjbsqcuvyr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mjbsqcuvyr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mjbsqcuvyr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mjbsqcuvyr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mjbsqcuvyr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mjbsqcuvyr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mjbsqcuvyr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mjbsqcuvyr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mjbsqcuvyr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mjbsqcuvyr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mjbsqcuvyr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mjbsqcuvyr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mjbsqcuvyr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mjbsqcuvyr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mjbsqcuvyr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mjbsqcuvyr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mjbsqcuvyr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mjbsqcuvyr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mjbsqcuvyr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mjbsqcuvyr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mjbsqcuvyr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mjbsqcuvyr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mjbsqcuvyr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mjbsqcuvyr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mjbsqcuvyr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mjbsqcuvyr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mjbsqcuvyr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mjbsqcuvyr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mjbsqcuvyr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mjbsqcuvyr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mjbsqcuvyr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mjbsqcuvyr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mjbsqcuvyr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mjbsqcuvyr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mjbsqcuvyr .gt_left {\n  text-align: left;\n}\n\n#mjbsqcuvyr .gt_center {\n  text-align: center;\n}\n\n#mjbsqcuvyr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mjbsqcuvyr .gt_font_normal {\n  font-weight: normal;\n}\n\n#mjbsqcuvyr .gt_font_bold {\n  font-weight: bold;\n}\n\n#mjbsqcuvyr .gt_font_italic {\n  font-style: italic;\n}\n\n#mjbsqcuvyr .gt_super {\n  font-size: 65%;\n}\n\n#mjbsqcuvyr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mjbsqcuvyr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mjbsqcuvyr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mjbsqcuvyr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mjbsqcuvyr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mjbsqcuvyr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mjbsqcuvyr .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#mjbsqcuvyr .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#mjbsqcuvyr div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"KipNYWxlKiogIApOID0gMiwwMDM=\"><span class='gt_from_md'><strong>Male</strong><br />\nN = 2,003</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"KipGZW1hbGUqKiAgCk4gPSAxLDc1Ng==\"><span class='gt_from_md'><strong>Female</strong><br />\nN = 1,756</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Gjennomsnittlig timelønn 1989</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">100 (32)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">79 (24)</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"3\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"TWVhbiAoU0Qp\"><span class='gt_from_md'>Mean (SD)</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n\n\n\nVi ser altså at menn hadde i gjennomsnitt høyere timelønn enn kvinner, nærmere bestemt 21 kroner mer. Dette kan vi også undersøke med lineær regresjon som følger:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_est2 <- lm(time89 ~ sex , data = abu89)\n\ncoef(lm_est2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)   sexFemale \n   99.84382   -20.75229 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nDet er altså slik at koeffisienten, $\\beta$, gir den samme differansen som en enkel sammenligning av to gjennomsnitt.\n\n\n\n\nVi har allerede sett på alder og lønn, så vi kan utvide dette til å inkludere kjønn samtidig i et scatterplot.\n\nGrafisk er det da greit å bruke farger og slik vise for menn og kvinner for seg. I `ggplot` spesifiseres da `group = sex` og at fargene skal settes etter sammen grupperingen `col = sex` slik:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(abu89, aes(x = age, y = time89, group = sex, col = sex)) +\n  geom_jitter(alpha = .4)\n```\n\n::: {.cell-output-display}\n![](lineaer_regresjon_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_est3 <- lm(time89 ~ sex + age, data = abu89)\n\ncoef(lm_est3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)   sexFemale         age \n 81.1014711 -20.6251051   0.4738042 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n### Interaksjonsledd \n\nDet kan tenkes at hvordan inntekten varierer med alder er *forskjellig* for menn og kvinner. I modellen ovenfor er det derimot antatt at denne er *lik*. Vi kan beskrive forskjellen i aldersgradienten i inntekt mellom menn og kvinner ved å inkludere interaksjonsledd (samspill) mellom kjønn og alder. \n\nDette gjør vi ved å spesifisere en regresjonslikning som følger: \n\n$$\ntime89 = \\alpha + \\beta_{1}(age) + \\beta_{2}(sex) + \\beta_{3}(age \\times sex)\n$$\nEller med andre ord: timelønn varierer med *alder* og *kjønn*, og *kombinasjonen* av disse. Merk hvordan dette skrives i R: \n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_est4 <- lm(time89 ~ sex + age + sex * age, data = abu89)\n\ncoef(lm_est4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)     sexFemale           age sexFemale:age \n   75.8535901    -9.9048054     0.6064699    -0.2719530 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\nMerk nå at referansekategorien for kjønn er menn, så den estimerte koeffisienten er for kvinner. Det betyr at i utregningen får menn verdien 0 og kvinner får verdien 1. Sette man det inn i regresjonslikningen for menn blir det da som følger: \n\n$$\ntime89 = \\alpha + \\beta_{1}(age) + \\beta_{2}\\times 0 + \\beta_{3}(age \\times 0)\n$$\nSiden alt som multipliseres med 0 blir 0 kan vi også skrive dette som: \n\n$$\ntime89 = \\alpha + \\beta_{1}(age) \n$$\nFor kvinner skal det derimot multipliseres med 1 og vi får: \n\n$$\ntime89 = \\alpha + \\beta_{1}(age) + \\beta_{2}\\times 1 + \\beta_{3}(age \\times 1)\n$$\nDet som multipliseres med 1 endres jo ikke, så da kan det skrives som:\n\n$$\ntime89 = \\alpha + \\beta_{1}(age) + \\beta_{2} + \\beta_{3}(age)\n$$\nMen siden vi har to termer for alder kan det forkortes til: \n\n$$\ntime89 = \\alpha + (\\beta_{1} + \\beta_{3})(age) + \\beta_{2} \n$$\nKortere sagt: forskjellen i stigningstallet mellom menn og kvinner er $\\beta_{3}$. I det empiriske eksempelet over betyr det at timelønn øker med alder for begge kjønn, men for kvinner øker det med 0.27 kroner mindre per år sammenlignet med menn. Eller sagt motsatt: menns lønn øker med 0.27 mer enn kvinner per år.  \n\n\n## Prediksjon \nLineær regresjon kan også brukes til *prediksjon* selv om dette i liten grad er hva samfunnsvitere bruker regresjonsmodeller til. Vanligvis vil vi primært være interessert i å tolke regresjonskoeffisientene som sammenligninger mellom grupper. Man kan si at man da er opptatt av *forklaringsvariablene*. Når man predikerer er man derimot opptatt av *utfallsvariabelen*. Hvis man skulle være interessert i temaer som maskinlæring, vil dette være en god inngang til det.^[f.eks. Et introduksjonskurs i maskinlæring som [SOS2901](https://www.uio.no/studier/emner/sv/iss/SOS2901/index.html) starter gjerne med nettopp prediksjon med lineær regresjon.] \n\n\n### Regne ut forventet verdi\nMerk at konstantleddet er tolkbart som forventet verdi på utfallsvariabelen når alle andre prediktorer er null. I eksempelet ovenfor med timelønn og klassetilhøringhet, er det altså ikke noen koeffisient for klasse I. Gjennomsnittlig timelønn i klasse I er når de andre dummyene er 0, altså 118.4 kroner. Gjennomsnittlig timelønn for klasse II er tilsvarende 118.4 + (-14.49) = 103.9.  \n\nHvis du skulle gjette timelønna til en person uten å vite noe annet enn klasseposisjon ville det være fornuftig å gjette på gjennomsnittet for denne klassen. Så vi kan bruke regresjonsmodeller til å regne ut gjennomsnittslønn for gitte verdier av forklaringsvariable. I dette eksempelet er det kanskje litt i overkant komplisert da vi jo også bare kunne regnet ut gjennomsnittet per gruppe i en enkel tabell. Det ville faktisk gitt akkurat samme resultat. Det er mer nyttig med kontinuerlige variable og mer kompliserte modeller. \n\nLa oss se på regresjonsmodellen for hvordan timelønn varierer med alder i stedet. Alder er kontinuerlig, så det er få personer på hvert alderstrinn. \n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(lm_est1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)         age \n 71.1101883   0.4828415 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nGjennomsnittlig timelønn ved 30 år vil da være 71.1 + 30 $\\times$ 0.5 = 86.1 kroner. Ved 35 år blir det tilsvarende 71.1 + 35 $\\times$ 0.5 = 88.6 kroner. \n\nDette kan vi altså regne ut for hånd, men man kan også bruke en r-funksjon, nemlig `predict`. Denne funksjonen tar som argument et regresjonsobjekt og en data.frame (altså et datasett eller tilsvarende struktur) med samme variabelnavn som ble brukt i opprinnelig regresjonsmodell.^[Hvis man ikke spesifiserer data.frame brukes opprinnelige data og predikerer for hver person. Det kan man også gjøre for å f.eks. regne ut residualer, men vi gjør ikke det her nå.]\n\n### Predikere for kontinuerlig variabel\nKoden nedenfor lager først et datasett med én variabel: alder med noen verdier man er interessert i utregning for. Så bruker man `mutate` til å lage en kolonne til med predikerte verdier. \n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyedata <- data.frame(age = c(17, 20, 30, 40, 50, 60))\n\nnyedata %>% \n  mutate(pred = predict(lm_est1, newdata = nyedata))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  age      pred\n1  17  79.31849\n2  20  80.76702\n3  30  85.59543\n4  40  90.42385\n5  50  95.25226\n6  60 100.08068\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n### Predikere kategorisk variabel\nTilsvarende kan vi predikere for kategoriske variable slik som ble benyttet i regresjonsmodellen for klasse. I det nye datasettet spesifiseres f.eks. alle nivåene av en factor-variabel med funksjonen `levels` og predikerer for disse. \n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyedata <- data.frame(klasse89 = levels(abu89$klasse89))\n\nnyedata %>% \n  mutate(pred = predict(est2, newdata = nyedata))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  klasse89      pred\n1     I Øvre serviceklasse 118.39851\n2   II Nedre serviceklasse 103.90773\n3   III Rutinefunksjonærer  75.50009\n4  V-VI Faglærte arbeidere  88.71063\n5 VIIa Ufaglærte arbeidere  81.44618\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n### Predikere for multippel regresjon\nNytten av predict-funksjonen kommer mer til sin rett ved mer kompliserte modeller. Her er et eksempel med flere variable: \n\n\nSå kan vi regne ut estimert gjennomsnittlig verdi for de ulike kombinasjonene av utvalgte verdier som følger: \n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyedata <- expand.grid(age = 30:35, \n                      sex = c(\"Female\", \"Male\"))\nnyedata %>% \n  mutate(pred = predict(lm_est3, newdata = nyedata))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   age    sex     pred\n1   30 Female 74.69049\n2   31 Female 75.16429\n3   32 Female 75.63810\n4   33 Female 76.11190\n5   34 Female 76.58571\n6   35 Female 77.05951\n7   30   Male 95.31560\n8   31   Male 95.78940\n9   32   Male 96.26320\n10  33   Male 96.73701\n11  34   Male 97.21081\n12  35   Male 97.68462\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\nFunksjonen `predict` fungerer på tilsvarende måte uansett hvor komplisert modellen måtte være. Men det kreves at det nye datasettet har samme variabelnavn og variabeltype som i opprinnelige data. \n\n\n\n\n## Pene tabeller og eksport til fil\nSlik resultatene ser ut med bruk av `summary` er forsåvidt fint, og du får den informasjonen du trenger. Men det er ikke særlig presentabelt som ferdig produkt i en analyse. Du trenger typisk to ting: 1) Samle flere regresjonsmodeller i samme tabell, og 2) gjøre tabellene penere og lettere å lese, og 3) eksportere til det tekstbehandlingsprogrammet du bruker, typisk Microsoft Word. \n\nR har en hel rekke funksjoner for dette. Det spiller egentlig ingen rolle hvilke funksjoner du bruker da det er noe smak og behag her, så det viktigste er at det fungerer rimelig greit for deg. Nedenfor presenteres tre pakker for dette formålet. Velg én av dem. Hvis du ikke har egne preferanser, så velg det første alternativet: {modelsummary}. Alle disse funksjonene håndterer svært mange typer modeller, gir gode muligheter for å ferdigstille tabellene fullstendig før eksport, og eksporterer til de formatene som er mest aktuelle. De har også mer avansert funksjonalitet som f.eks. å rapportere robuste standardfeil (av forskjellig type) i stedet for vanlige standardfeil (dette er pensum på SOS4020).\n\nVi vil som regel ha behov for å flytte resultatene over til et tekstbehandlingsprogram. En strategi som går ut på \"klipp og lim\" eller skjermbilde etc er uaktuelt og må unngås for nærmest enhver pris.[^linearregresjon-6] Resultatene skal skrives til en fil på en effektiv måte. Det er en fordel om tabellene da ser ganske ok ut i utgangspunktet og du kan bruke samme prosedyre for å eksportere til flere typer format hvis behovet skulle melde seg. Det er jo MS Word som er viktigst for de fleste, mens de øvrige formatene nedenfor er for spesielt interessert - men noen av dere vil kanskje bli det på et senere tidspunkt. De viktigste formatene som er:\n\n[^linearregresjon-6]: Hvis du blir tatt i å gjøre slikt vil faglærer sette fyr på datamaskinen din som straff.\n\n-   MS Word - det vanligste tekstbehandlingsprogrammet som de aller fleste av dere bruker.\n-   rtf - rikt tekstformat. Er et enklere format som fungerer på tvers av de fleste programmer. Kan brukes i Word også.\n-   html - for websider\n-   latex - for mer tekniske dokumenter, særlig hvis du har mye formler og stæsj\n-   Markdown/Quarto - for dynamiske dokumenter med integrert R-kode og tekst, og kan eksportere ferdig dokument til alle ovennevnte formater[^linearregresjon-7] Det som fungerer med Markdown fungerer også med Quarto for samme formål.\n\n[^linearregresjon-7]: F.eks. dette dokumentet er skrevet i Quarto\n\n\n### Alt 1: Bruke `modelsummary()`\n\nEksporterer til bl.a. følgende formater: Word, rtf, html, latex, markdown\n\nFordel: Gir pene og oversiktlige tabeller med enkel kode, og relativt enkelt å  modifisere videre. Eksporterer direkte til alle viktigste formater. \nKan også lett integreres med andre eksterne verktøy, først og fremst \"grammar of tables\" i pakket {gt} \nUlempe: \n\n\nHer er kode for en enkel tabell med to regresjonsmodeller som vist ovenfor. Merk at objektene med regresjonsresultatene må legges inni funksjonen `list()`. \n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(modelsummary)\nmodelsummary(list(lm_est2, lm_est3))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_a7lkpeyys05l2hp9t529 = TinyTable.createTableFunctions(\"tinytable_a7lkpeyys05l2hp9t529\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '14', j: 2 }, { i: '14', j: 3 } ], css_id: 'tinytable_css_v5pyahu6kifgtbifkaub',}, \n          { positions: [ { i: '6', j: 2 }, { i: '6', j: 3 } ], css_id: 'tinytable_css_3ke9g2ajt85wnw2g7e3t',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '13', j: 3 } ], css_id: 'tinytable_css_ka9cre1gapqw5dabokpp',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_fysmpbhwivzkxeqks3qc',}, \n          { positions: [ { i: '14', j: 1 } ], css_id: 'tinytable_css_oiuz1junsststhkx3ikc',}, \n          { positions: [ { i: '6', j: 1 } ], css_id: 'tinytable_css_90jhsu7eoieek16b9bo5',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 } ], css_id: 'tinytable_css_1svibdyzmdaem2t3yd06',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_05mkhcge9yauwpjsyvw0',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_a7lkpeyys05l2hp9t529.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_a7lkpeyys05l2hp9t529 td.tinytable_css_v5pyahu6kifgtbifkaub, #tinytable_a7lkpeyys05l2hp9t529 th.tinytable_css_v5pyahu6kifgtbifkaub {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_a7lkpeyys05l2hp9t529 td.tinytable_css_3ke9g2ajt85wnw2g7e3t, #tinytable_a7lkpeyys05l2hp9t529 th.tinytable_css_3ke9g2ajt85wnw2g7e3t {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_a7lkpeyys05l2hp9t529 td.tinytable_css_ka9cre1gapqw5dabokpp, #tinytable_a7lkpeyys05l2hp9t529 th.tinytable_css_ka9cre1gapqw5dabokpp { text-align: center }\n    #tinytable_a7lkpeyys05l2hp9t529 td.tinytable_css_fysmpbhwivzkxeqks3qc, #tinytable_a7lkpeyys05l2hp9t529 th.tinytable_css_fysmpbhwivzkxeqks3qc {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_a7lkpeyys05l2hp9t529 td.tinytable_css_oiuz1junsststhkx3ikc, #tinytable_a7lkpeyys05l2hp9t529 th.tinytable_css_oiuz1junsststhkx3ikc {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_a7lkpeyys05l2hp9t529 td.tinytable_css_90jhsu7eoieek16b9bo5, #tinytable_a7lkpeyys05l2hp9t529 th.tinytable_css_90jhsu7eoieek16b9bo5 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_a7lkpeyys05l2hp9t529 td.tinytable_css_1svibdyzmdaem2t3yd06, #tinytable_a7lkpeyys05l2hp9t529 th.tinytable_css_1svibdyzmdaem2t3yd06 { text-align: left }\n    #tinytable_a7lkpeyys05l2hp9t529 td.tinytable_css_05mkhcge9yauwpjsyvw0, #tinytable_a7lkpeyys05l2hp9t529 th.tinytable_css_05mkhcge9yauwpjsyvw0 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_a7lkpeyys05l2hp9t529\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">(1)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">(2)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">99.844</td>\n                  <td data-row=\"1\" data-col=\"3\">81.101</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.637)</td>\n                  <td data-row=\"2\" data-col=\"3\">(1.585)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">sexFemale</td>\n                  <td data-row=\"3\" data-col=\"2\">-20.752</td>\n                  <td data-row=\"3\" data-col=\"3\">-20.625</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.932)</td>\n                  <td data-row=\"4\" data-col=\"3\">(0.912)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">age</td>\n                  <td data-row=\"5\" data-col=\"2\"></td>\n                  <td data-row=\"5\" data-col=\"3\">0.474</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\"></td>\n                  <td data-row=\"6\" data-col=\"3\">(0.037)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"7\" data-col=\"2\">3759</td>\n                  <td data-row=\"7\" data-col=\"3\">3759</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">R2</td>\n                  <td data-row=\"8\" data-col=\"2\">0.117</td>\n                  <td data-row=\"8\" data-col=\"3\">0.154</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">R2 Adj.</td>\n                  <td data-row=\"9\" data-col=\"2\">0.116</td>\n                  <td data-row=\"9\" data-col=\"3\">0.153</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\">AIC</td>\n                  <td data-row=\"10\" data-col=\"2\">35854.9</td>\n                  <td data-row=\"10\" data-col=\"3\">35694.9</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">BIC</td>\n                  <td data-row=\"11\" data-col=\"2\">35873.6</td>\n                  <td data-row=\"11\" data-col=\"3\">35719.8</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\">Log.Lik.</td>\n                  <td data-row=\"12\" data-col=\"2\">-17924.434</td>\n                  <td data-row=\"12\" data-col=\"3\">-17843.437</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">F</td>\n                  <td data-row=\"13\" data-col=\"2\">496.278</td>\n                  <td data-row=\"13\" data-col=\"3\">341.699</td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\">RMSE</td>\n                  <td data-row=\"14\" data-col=\"2\">28.49</td>\n                  <td data-row=\"14\" data-col=\"3\">27.88</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n\n\n\n\n\nDenne tabellen inneholder mer enn du er interessert i. Nedre del av tabellen inneholder \"goodness of fit\" statistikker, altså mål på hvordan modellen passer til dataene. Det finnes mange slike, men ingen grunn til å gå seg vill i disse her. De kan fjernes med argumentet `gof_omit = ` og så angis statistikkene med de navnene du ser i tabellen. Det skrives på en spesiell måte: som en tekststreng angitt med anførselstegn rundt, og `|` mellom hver. I koden nedenfor beholdes kun antall observasjoner, $r^2$ og $F$.^[Øvrige statistikker har selvsagt sitt bruksområde. De nevnte holder for de fleste formål.] \n\nVi gjør et par andre justeringer samtidig for å demonstrere noe funksjonalitet. I stedet for å oppgi estimatet og standardfeil på forskjellig linje kan vi spesifisere å ha det på samme linje med argumentet `estimate = `. Merk at den statistikken du vil rapportere settes i parentes {...} og mellomrom og parentes er ellers som det står. Man har også andre valg, derav det vanligste i bruk er å angi *p*-verdier eller *stjerner* for å vise disse på en forenklet måte. Det angis ved `{p.value}` eller `{stars}` på tilsvarende måte.  \n\nI stedet for standardfeil på egen linje er det her angitt konfidensintervall på neste linje. For konfidensintervall vil det som forvalg være 95%, men vi kan angi f.eks. 99% konfidensintervall i stedet ved `conf_level = `. \nHvis man ikke vil ha noe på neste linje kan man angi `statistic = NULL` i stedet. Man kan også velge å sette inn `p.value` eller `stars` på denne linjen.\n\nMerk at utfallsvariabelen i modellene er timelønn i kroner. I forrige tabell ble estimatene gitt med tre desimaler. Det er i overkant mange desimaler. En desimal er mer passende og nedenfor endres dette med `fmt = `. \n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(list(lm_est2, lm_est3), \n             fmt = 1,\n             estimate = \"{estimate} ({std.error})\",\n             statistic = 'conf.int', \n             conf_level = .99, \n             gof_omit = 'DF|Deviance|R2 Adj.|AIC|BIC|Log.Lik.|RMSE')\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_b57zayajsfvpjs7otkxz = TinyTable.createTableFunctions(\"tinytable_b57zayajsfvpjs7otkxz\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '9', j: 2 }, { i: '9', j: 3 } ], css_id: 'tinytable_css_ey77nwifrilfm5b3xqoh',}, \n          { positions: [ { i: '6', j: 2 }, { i: '6', j: 3 } ], css_id: 'tinytable_css_358ufyl5ioemeegcsn4n',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 } ], css_id: 'tinytable_css_n4tsuy8yyppz25ml6969',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_8y6gn7xga9n579i9kduf',}, \n          { positions: [ { i: '9', j: 1 } ], css_id: 'tinytable_css_rjyu3setxjoyrzq94t1v',}, \n          { positions: [ { i: '6', j: 1 } ], css_id: 'tinytable_css_gpkmx2gdq7z18a9gx1l7',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 } ], css_id: 'tinytable_css_5077rq6w4eerepq0qbwl',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_7ra8n2o343h2r85p3vfl',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_b57zayajsfvpjs7otkxz.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_b57zayajsfvpjs7otkxz td.tinytable_css_ey77nwifrilfm5b3xqoh, #tinytable_b57zayajsfvpjs7otkxz th.tinytable_css_ey77nwifrilfm5b3xqoh {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_b57zayajsfvpjs7otkxz td.tinytable_css_358ufyl5ioemeegcsn4n, #tinytable_b57zayajsfvpjs7otkxz th.tinytable_css_358ufyl5ioemeegcsn4n {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_b57zayajsfvpjs7otkxz td.tinytable_css_n4tsuy8yyppz25ml6969, #tinytable_b57zayajsfvpjs7otkxz th.tinytable_css_n4tsuy8yyppz25ml6969 { text-align: center }\n    #tinytable_b57zayajsfvpjs7otkxz td.tinytable_css_8y6gn7xga9n579i9kduf, #tinytable_b57zayajsfvpjs7otkxz th.tinytable_css_8y6gn7xga9n579i9kduf {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_b57zayajsfvpjs7otkxz td.tinytable_css_rjyu3setxjoyrzq94t1v, #tinytable_b57zayajsfvpjs7otkxz th.tinytable_css_rjyu3setxjoyrzq94t1v {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_b57zayajsfvpjs7otkxz td.tinytable_css_gpkmx2gdq7z18a9gx1l7, #tinytable_b57zayajsfvpjs7otkxz th.tinytable_css_gpkmx2gdq7z18a9gx1l7 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_b57zayajsfvpjs7otkxz td.tinytable_css_5077rq6w4eerepq0qbwl, #tinytable_b57zayajsfvpjs7otkxz th.tinytable_css_5077rq6w4eerepq0qbwl { text-align: left }\n    #tinytable_b57zayajsfvpjs7otkxz td.tinytable_css_7ra8n2o343h2r85p3vfl, #tinytable_b57zayajsfvpjs7otkxz th.tinytable_css_7ra8n2o343h2r85p3vfl {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_b57zayajsfvpjs7otkxz\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">(1)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">(2)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">99.8 (0.6)</td>\n                  <td data-row=\"1\" data-col=\"3\">81.1 (1.6)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">[98.2, 101.5]</td>\n                  <td data-row=\"2\" data-col=\"3\">[77.0, 85.2]</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">sexFemale</td>\n                  <td data-row=\"3\" data-col=\"2\">-20.8 (0.9)</td>\n                  <td data-row=\"3\" data-col=\"3\">-20.6 (0.9)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">[-23.2, -18.4]</td>\n                  <td data-row=\"4\" data-col=\"3\">[-23.0, -18.3]</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">age</td>\n                  <td data-row=\"5\" data-col=\"2\"></td>\n                  <td data-row=\"5\" data-col=\"3\">0.5 (0.0)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\"></td>\n                  <td data-row=\"6\" data-col=\"3\">[0.4, 0.6]</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"7\" data-col=\"2\">3759</td>\n                  <td data-row=\"7\" data-col=\"3\">3759</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">R2</td>\n                  <td data-row=\"8\" data-col=\"2\">0.117</td>\n                  <td data-row=\"8\" data-col=\"3\">0.154</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">F</td>\n                  <td data-row=\"9\" data-col=\"2\">496.278</td>\n                  <td data-row=\"9\" data-col=\"3\">341.699</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n\n\n\n\n\n\nTo siste ting å ta med her er å endre navn på variablene til noe mer presentabelt og eksportere til Word. Med argumentet `coef_rename = ` angis variabelen slik den ser ut i output og spesifiserer hva du vil skal stå. Koden nedenfor viser eksempel. \n\nFor å eksportere til Word settes `output = ` med filbane og filnavn, og der filhalen *.docx* angir Word format. Du kan eksportere til annet format ved å angi annen filhale f.eks. .rtf eller .html. \n\n\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_lhgvl6e0nqx4l61sbt7j = TinyTable.createTableFunctions(\"tinytable_lhgvl6e0nqx4l61sbt7j\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '9', j: 2 }, { i: '9', j: 3 } ], css_id: 'tinytable_css_jvzdrdwhgfeduvvmytxc',}, \n          { positions: [ { i: '6', j: 2 }, { i: '6', j: 3 } ], css_id: 'tinytable_css_1egatt077ps4fiahula1',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 } ], css_id: 'tinytable_css_sfukz3x425jtap6l9rf8',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_s7c838adjdz3divqockf',}, \n          { positions: [ { i: '9', j: 1 } ], css_id: 'tinytable_css_q2oo2j44kgmd72ufq1rq',}, \n          { positions: [ { i: '6', j: 1 } ], css_id: 'tinytable_css_2onh1mob3r0yf4glej1t',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 } ], css_id: 'tinytable_css_63wlk1sro3b88l5348ea',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_6mzmetgsxrrnzt6mledd',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_lhgvl6e0nqx4l61sbt7j.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_lhgvl6e0nqx4l61sbt7j td.tinytable_css_jvzdrdwhgfeduvvmytxc, #tinytable_lhgvl6e0nqx4l61sbt7j th.tinytable_css_jvzdrdwhgfeduvvmytxc {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_lhgvl6e0nqx4l61sbt7j td.tinytable_css_1egatt077ps4fiahula1, #tinytable_lhgvl6e0nqx4l61sbt7j th.tinytable_css_1egatt077ps4fiahula1 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_lhgvl6e0nqx4l61sbt7j td.tinytable_css_sfukz3x425jtap6l9rf8, #tinytable_lhgvl6e0nqx4l61sbt7j th.tinytable_css_sfukz3x425jtap6l9rf8 { text-align: center }\n    #tinytable_lhgvl6e0nqx4l61sbt7j td.tinytable_css_s7c838adjdz3divqockf, #tinytable_lhgvl6e0nqx4l61sbt7j th.tinytable_css_s7c838adjdz3divqockf {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_lhgvl6e0nqx4l61sbt7j td.tinytable_css_q2oo2j44kgmd72ufq1rq, #tinytable_lhgvl6e0nqx4l61sbt7j th.tinytable_css_q2oo2j44kgmd72ufq1rq {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_lhgvl6e0nqx4l61sbt7j td.tinytable_css_2onh1mob3r0yf4glej1t, #tinytable_lhgvl6e0nqx4l61sbt7j th.tinytable_css_2onh1mob3r0yf4glej1t {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_lhgvl6e0nqx4l61sbt7j td.tinytable_css_63wlk1sro3b88l5348ea, #tinytable_lhgvl6e0nqx4l61sbt7j th.tinytable_css_63wlk1sro3b88l5348ea { text-align: left }\n    #tinytable_lhgvl6e0nqx4l61sbt7j td.tinytable_css_6mzmetgsxrrnzt6mledd, #tinytable_lhgvl6e0nqx4l61sbt7j th.tinytable_css_6mzmetgsxrrnzt6mledd {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_lhgvl6e0nqx4l61sbt7j\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">(1)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">(2)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Konstant</td>\n                  <td data-row=\"1\" data-col=\"2\">99.8 (0.6)</td>\n                  <td data-row=\"1\" data-col=\"3\">81.1 (1.6)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">[98.2, 101.5]</td>\n                  <td data-row=\"2\" data-col=\"3\">[77.0, 85.2]</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Kvinne</td>\n                  <td data-row=\"3\" data-col=\"2\">-20.8 (0.9)</td>\n                  <td data-row=\"3\" data-col=\"3\">-20.6 (0.9)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">[-23.2, -18.4]</td>\n                  <td data-row=\"4\" data-col=\"3\">[-23.0, -18.3]</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Alder</td>\n                  <td data-row=\"5\" data-col=\"2\"></td>\n                  <td data-row=\"5\" data-col=\"3\">0.5 (0.0)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\"></td>\n                  <td data-row=\"6\" data-col=\"3\">[0.4, 0.6]</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"7\" data-col=\"2\">3759</td>\n                  <td data-row=\"7\" data-col=\"3\">3759</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">R2</td>\n                  <td data-row=\"8\" data-col=\"2\">0.117</td>\n                  <td data-row=\"8\" data-col=\"3\">0.154</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">F</td>\n                  <td data-row=\"9\" data-col=\"2\">496.278</td>\n                  <td data-row=\"9\" data-col=\"3\">341.699</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(list(lm_est2, lm_est3), \n             fmt = 1,\n             estimate = \"{estimate} ({std.error})\",\n             statistic = 'conf.int', \n             conf_level = .99, \n             gof_omit = 'DF|Deviance|R2 Adj.|AIC|BIC|Log.Lik.|RMSE', \n             coef_rename = c(\"sexFemale\" = \"Kvinne\", \n                                   \"age\" = \"Alder\", \n                                  \"(Intercept)\" = \"Konstant\"), \n             output = \"output/reg_table.docx\")\n```\n:::\n\n\n\n\n\n\n\n\nMerk at Word vil vise tabellen med de fonter etc som er forvalgt for Word. Dette kan du endre i Word etterpå. Det er en rekke funksjoner i Word for å formattere tabeller som du kan bruke. \n\nPakken {modelsummary} har også en rekke andre funksjoner for å redigere tabeller som du kan utforske ved behov. For avanserte brukere kan man også gjøre om tabellen til et gt-objekt og redigere videre med pakken {gt} eller tilsvarende med pakken {flextable}. Det er altså tilnærmet uendelige muligheter for avanserte tabeller. Dette går imidlertid langt utenfor hva de fleste av dere vil trenge. {modelsummary} har [egen hjemmeside](https://vincentarelbundock.github.io/modelsummary/index.html) med mer detaljer og instruksjoner.\n\n\n\n### Alt 2: Bruke {stargazer}\nMange R-brukere foretrekker pakken {stargazer}. Dette er en noe eldre funksjon og er derfor godt etablert. \n\nEksporterer til bl.a. følgende formater: rtf, html, latex, markdown\n\nFordel: Er en stand-alone pakke men gir enkelt veldig fine tabeller som antakeligvis er det du trenger Ulempe: Eksport til Word er ikke den beste, men god nok.\n\nStargazer lager tabeller i kun tre formater: latex, html, og ren tekst. Vi velger derfor `type = \"text\"` for at det skal se ok ut her. \n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(stargazer)\nstargazer(lm_est2, lm_est3, type = \"text\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=======================================================================\n                                    Dependent variable:                \n                    ---------------------------------------------------\n                                          time89                       \n                               (1)                       (2)           \n-----------------------------------------------------------------------\nsexFemale                  -20.752***                -20.625***        \n                             (0.932)                   (0.912)         \n                                                                       \nage                                                   0.474***         \n                                                       (0.037)         \n                                                                       \nConstant                    99.844***                 81.101***        \n                             (0.637)                   (1.585)         \n                                                                       \n-----------------------------------------------------------------------\nObservations                  3,759                     3,759          \nR2                            0.117                     0.154          \nAdjusted R2                   0.116                     0.153          \nResidual Std. Error    28.495 (df = 3757)        27.891 (df = 3756)    \nF Statistic         496.278*** (df = 1; 3757) 341.699*** (df = 2; 3756)\n=======================================================================\nNote:                                       *p<0.1; **p<0.05; ***p<0.01\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nVi kan modifisere tabellen tilsvarende som vi gjorde med {modelsummary}. Forklaringer av de enkelte argumenter finnes i [manualen for stargazer](https://cran.r-project.org/web/packages/stargazer/stargazer.pdf). \n\n`covariate.labels = ` Angir teksten for variabelnavn. Merk at det oppgis i den *rekkefølgen* det skal stå, så være veldig nøye hvis du har mange variable! \n`report = ` angir hva som skal inngå i tabellen, der hver bokstav viser til spesifikke deler: v = variabelnavn, c = koeffisient/estimat, s = standardfeil. \n`single.row = ` setter statistikkene på samme linje fremfor under hverandre.\n`keep.stat = ` angir hvilke \"model fit statistics\" som skal rapporteres. Hvis du skriver \"all\" her får du en lang remse tilsvarende vi fikk med {modelsummary}. \n`digits = ` angir antall desimaler \n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstargazer(lm_est2, lm_est3, \n          type = \"text\", \n          covariate.labels = c(\"Kvinne\", \"Alder\", \"Konstant\"),\n          report = \"vcs\",\n          single.row = TRUE, \n          keep.stat = c(\"n\",\"rsq\", \"ser\"),\n          digits = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=====================================================\n                           Dependent variable:       \n                    ---------------------------------\n                                 time89              \n                          (1)              (2)       \n-----------------------------------------------------\nKvinne                -20.8 (0.9)      -20.6 (0.9)   \nAlder                                   0.5 (0.04)   \nKonstant               99.8 (0.6)       81.1 (1.6)   \n-----------------------------------------------------\nObservations             3,759            3,759      \nR2                        0.1              0.2       \nResidual Std. Error 28.5 (df = 3757) 27.9 (df = 3756)\n=====================================================\nNote:                     *p<0.1; **p<0.05; ***p<0.01\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nFor å eksportere til Word kan man bruke rikt tekstformat (.rtf) eller html. rtf-formatet er som navnet tilsier ren tekst og selv om det ser greit ut, så er videre redigering i et tekstbehandlingsprogram krøkete. (Prøv og se selv). Bruk heller html fordi da beholdes tabell-strukturen. Du kan åpne html-tabeller fra Word og redigere videre der ved behov. \n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstargazer(lm_est2, lm_est3, \n          type = \"text\",\n          covariate.labels = c(\"Kvinne\", \"Alder\", \"Konstant\"),\n          report = \"vcs\",\n          single.row = TRUE, \n          keep.stat = c(\"n\",\"rsq\", \"ser\"),\n          digits = 1, \n          out = \"output/reg_starg.html\")\n```\n:::\n\n\n\n\n\n\n\n\n\nMer detaljer finner du i [{stargazer} sin vignette](https://cran.r-project.org/web/packages/stargazer/vignettes/stargazer.pdf).\n\n\n\n### Alt 3: Bruke {gtsummary}\nVi har tidligere brukt {gtsummary} for å lage deskriptive tabeller, som er det pakken er best til. Men den kan også lage gode regresjonstabeller. Det er imidlertid en stor ulempe for nybegynnere i R: det er ganske krøkete å sette sammen flere regresjonsmodeller i en samlet tabell. Derfor er rådet å *ikke bruke* denne pakken med mindre du har veldig lyst til å prøve. \n\nFordel med å bruke denne pakken er at man slipper å lære enda en ny pakke og slik sett ha ett sett med konsistent syntaks. En mulighet er selvsagt å ikke lage tabellene så ferdig i R, men eksportere til Word og redigere ferdig der mer manuelt. \n\n{gtsummary} kan eksportere til følgende formater: Word, rtf, html, latex og markdown. Resultatene kan også lett integreres med andre funksjoner, først og fremst \"grammar of tables\" i pakket {gt} og {flextable} - altså for mer avanserte ting som vi ikke dekker her.\n\nPrinsippet er å lage hver tabell for seg og så slå dem sammen med `tbl_merge` etterpå. Det innebærer en del mer kode, rett og slett. I utgangspunktet virker det ganske greit, men det er alltid en del småting som krever litt mer. \n\nFølgende kode lager først en ryddig tabell for hver regresionsmodell og så kobler sammen disse to tabellene. \n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_tab1 <- tbl_regression(lm_est2, intercept = T, \n                          estimate_fun = function(x) style_number(x, digits = 1),\n                          show_single_row = \"sex\",\n                          label = list(sex ~ \"Kvinne\")) %>% \n    add_glance_table(include = c(nobs, r.squared, sigma))\n                     \nlm_tab2 <- tbl_regression(lm_est3, intercept = T,\n                          estimate_fun = function(x) style_number(x, digits = 1), \n                          show_single_row = \"sex\",\n                          label = list(age ~ \"Alder\", sex ~ \"Kvinne\")) %>% \n    add_glance_table(include = c(nobs, r.squared, sigma)\n  )\n\n\ntbl_merge(tbls = list(lm_tab1, lm_tab2)) %>% \n  modify_table_body(\n    ~.x %>% \n      dplyr::arrange(\n        row_type == \"glance_statistic\", # sort glance table to bottom\n        var_label                       # sort by the variable label (a hidden column) \n      )\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe number rows in the tables to be merged do not match, which may result in\nrows appearing out of order.\nℹ See `tbl_merge()` (`?gtsummary::tbl_merge()`) help file for details. Use\n  `quiet=TRUE` to silence message.\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"etstdxgppe\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#etstdxgppe table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#etstdxgppe thead, #etstdxgppe tbody, #etstdxgppe tfoot, #etstdxgppe tr, #etstdxgppe td, #etstdxgppe th {\n  border-style: none;\n}\n\n#etstdxgppe p {\n  margin: 0;\n  padding: 0;\n}\n\n#etstdxgppe .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#etstdxgppe .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#etstdxgppe .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#etstdxgppe .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#etstdxgppe .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#etstdxgppe .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#etstdxgppe .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#etstdxgppe .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#etstdxgppe .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#etstdxgppe .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#etstdxgppe .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#etstdxgppe .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#etstdxgppe .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#etstdxgppe .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#etstdxgppe .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#etstdxgppe .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#etstdxgppe .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#etstdxgppe .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#etstdxgppe .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#etstdxgppe .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#etstdxgppe .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#etstdxgppe .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#etstdxgppe .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#etstdxgppe .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#etstdxgppe .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#etstdxgppe .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#etstdxgppe .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#etstdxgppe .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#etstdxgppe .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#etstdxgppe .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#etstdxgppe .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#etstdxgppe .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#etstdxgppe .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#etstdxgppe .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#etstdxgppe .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#etstdxgppe .gt_left {\n  text-align: left;\n}\n\n#etstdxgppe .gt_center {\n  text-align: center;\n}\n\n#etstdxgppe .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#etstdxgppe .gt_font_normal {\n  font-weight: normal;\n}\n\n#etstdxgppe .gt_font_bold {\n  font-weight: bold;\n}\n\n#etstdxgppe .gt_font_italic {\n  font-style: italic;\n}\n\n#etstdxgppe .gt_super {\n  font-size: 65%;\n}\n\n#etstdxgppe .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#etstdxgppe .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#etstdxgppe .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#etstdxgppe .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#etstdxgppe .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#etstdxgppe .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#etstdxgppe .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#etstdxgppe .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#etstdxgppe div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"level 1; estimate_1\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipUYWJsZSAxKio=\"><span class='gt_from_md'><strong>Table 1</strong></span></span></div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"level 1; estimate_2\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipUYWJsZSAyKio=\"><span class='gt_from_md'><strong>Table 2</strong></span></span></div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate_1\"><span data-qmd-base64=\"KipCZXRhKio=\"><span class='gt_from_md'><strong>Beta</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low_1\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value_1\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate_2\"><span data-qmd-base64=\"KipCZXRhKio=\"><span class='gt_from_md'><strong>Beta</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low_2\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value_2\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">99.8</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">98.6, 101.1</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><0.001</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">81.1</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">78.0, 84.2</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Alder</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">0.5</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">0.4, 0.5</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Kvinne</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">-20.8</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">-22.6, -18.9</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><0.001</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">-20.6</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">-22.4, -18.8</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\">No. Obs.</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\">3,759</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\">3,759</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\"><br /></td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">R²</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">0.117</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">0.154</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Sigma</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">28.5</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">27.9</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"7\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uOiBDSSA9IENvbmZpZGVuY2UgSW50ZXJ2YWw=\"><span class='gt_from_md'>Abbreviation: CI = Confidence Interval</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n",
    "supporting": [
      "lineaer_regresjon_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}