{
  "hash": "d95af67be4a75d21955e7e66e1c165b1",
  "result": {
    "engine": "knitr",
    "markdown": "# Kontrollere for bakenforliggende variable\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(haven)\nlibrary(modelsummary)\n```\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nI forrige kapittel så vi hvordan vi kan estimere regresjonsmodeller med en eller flere forklaringsvariable. Men *hvorfor* vil vi ha flere variable i modellen? Det handler om noe av det mest sentrale i kvantitativ samfunnsvitenskap: å kontrollere for bakenforliggende variable. I dette kapittelet skal vi se på hva det betyr, hvorfor det er viktig, og hvordan vi gjør det i praksis.\n\n\n## Simpsons paradoks: Når helheten lyver\nLa oss starte med et tankeksperiment. Tenk deg at du sammenligner to sykehus for å finne ut hvilket som er best. Sykehus A har høyere dødelighet enn sykehus B totalt sett. Men når du ser på lette og alvorlige tilfeller *hver for seg*, er sykehus A faktisk bedre i *begge* gruppene. Hvordan er det mulig?\n\nForklaringen er at sykehus A er et spesialistsykehus som tar imot de mest alvorlige pasientene. Alvorlige tilfeller har naturligvis høyere dødelighet uansett sykehus. Når vi *kontrollerer for* alvorlighetsgrad -- altså sammenligner likt med likt -- snur bildet seg.\n\nDette fenomenet kalles *Simpsons paradoks*: en sammenheng som går i en retning totalt sett kan snu når man deler opp etter en tredje variabel. Det er ikke bare et teoretisk kuriosum. Det skjer hele tiden i samfunnsvitenskapelige data, og det er en av hovedgrunnene til at vi bruker multippel regresjon.\n\n\n## Hva betyr det å \"kontrollere for\" en variabel?\nUttrykket \"kontrollere for\" er noe man hører hele tiden i metodeundervisning. Men hva betyr det egentlig?\n\nKort sagt betyr det at vi sammenligner grupper som er *like* på den variabelen vi kontrollerer for, men *forskjellige* på den variabelen vi er interessert i. Hvis vi kontrollerer for sosial klasse i en analyse av kjønnsforskjeller i lønn, betyr det at vi sammenligner menn og kvinner *innenfor samme klasse*. Vi sammenligner altså likt med likt, så godt det lar seg gjøre.\n\nI praksis gjør multippel regresjon dette for oss matematisk: når vi legger til en variabel i modellen, \"renser\" vi sammenhengen mellom de andre variablene og utfallet for den variabelen vi la til. Det er dette vi mener med å kontrollere for.\n\n\n## Praktisk eksempel: Kjønnsgapet i lønn\nLa oss se på et konkret eksempel med abu89-datasettet. Vi starter med den enkle sammenhengen mellom kjønn og timelønn.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod1 <- lm(time89 ~ female, data = abu89)\ncoef(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      female \n   99.84382   -20.75229 \n```\n\n\n:::\n:::\n\n\nKoeffisienten for `female` viser forskjellen i gjennomsnittlig timelønn mellom kvinner og menn. Kvinner tjente altså betydelig mindre enn menn. Men er hele denne forskjellen fordi arbeidsgivere betaler kvinner mindre? Eller kan noe av forskjellen skyldes at menn og kvinner i gjennomsnitt har forskjellige yrker, utdanninger og klasseposisjoner?\n\nLa oss legge til sosial klasse i modellen:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod2 <- lm(time89 ~ female + klasse89, data = abu89)\ncoef(mod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     (Intercept)                           female \n                       122.63676                        -18.19952 \n  klasse89II Nedre serviceklasse   klasse89III Rutinefunksjonærer \n                       -10.39630                        -32.70807 \n klasse89V-VI Faglærte arbeidere klasse89VIIa Ufaglærte arbeidere \n                       -32.60689                        -34.03860 \n```\n\n\n:::\n:::\n\n\nLegg merke til hva som skjedde med koeffisienten for `female`. Den ble mindre (i absoluttverdi). Det betyr at *noe* av lønnsforskjellen mellom menn og kvinner kan tilskrives at de befinner seg i ulike klasseposisjoner. Når vi sammenligner menn og kvinner *i samme klasse*, er forskjellen mindre.\n\nVi kan utvide enda mer og legge til utdanning:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod3 <- lm(time89 ~ female + klasse89 + ed, data = abu89)\ncoef(mod3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     (Intercept)                           female \n                      104.807681                       -17.197749 \n  klasse89II Nedre serviceklasse   klasse89III Rutinefunksjonærer \n                       -4.945598                       -20.364392 \n klasse89V-VI Faglærte arbeidere klasse89VIIa Ufaglærte arbeidere \n                      -19.696567                       -19.227326 \n                              ed \n                        2.812244 \n```\n\n\n:::\n:::\n\n\nOgså her kan vi se at koeffisienten for `female` endrer seg noe når vi legger til flere kontrollvariable.\n\n\n## Bivariat vs. multippel regresjon\nI en *bivariat* regresjon (kun en forklaringsvariabel) beskriver koeffisienten den *totale* sammenhengen mellom variabelen og utfallet. Denne sammenhengen kan inneholde både en direkte effekt og indirekte effekter via andre variable.\n\nI en *multippel* regresjon (flere forklaringsvariable) beskriver koeffisienten sammenhengen mellom variabelen og utfallet *gitt at de andre variablene holdes konstant*. Det er dette \"kontrollere for\" betyr i praksis.\n\nForskjellen kan oppsummeres slik:\n\n- **Bivariat**: Hva er den gjennomsnittlige lønnsforskjellen mellom menn og kvinner?\n- **Multippel**: Hva er den gjennomsnittlige lønnsforskjellen mellom menn og kvinner *som er i samme sosiale klasse og har samme utdanningsnivå*?\n\nDet er viktig å forstå at begge spørsmålene kan være relevante. Det avhenger av hva du er interessert i.\n\n\n## Sammenligne modeller med `modelsummary()`\nFor å virkelig se hva som skjer når vi legger til kontrollvariable er det nyttig å sette modellene ved siden av hverandre i en tabell. Da kan vi direkte se hvordan koeffisienten for `female` endres.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(list(\"Bivariat\" = mod1,\n                  \"Med klasse\" = mod2,\n                  \"Med klasse og utd.\" = mod3),\n             fmt = 1,\n             estimate = \"{estimate} ({std.error})\",\n             statistic = NULL,\n             gof_omit = 'DF|Deviance|R2 Adj.|AIC|BIC|Log.Lik.|RMSE',\n             coef_rename = c(\"female\" = \"Kvinne\",\n                             \"educ\" = \"Utdanning (år)\",\n                             \"(Intercept)\" = \"Konstant\"))\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tblr}[         %% tabularray outer open\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]Q[]},\nhline{2}={1-4}{solid, black, 0.05em},\nhline{9}={1-4}{solid, black, 0.05em},\nhline{1}={1-4}{solid, black, 0.1em},\nhline{12}={1-4}{solid, black, 0.1em},\ncolumn{2-4}={}{halign=c},\ncolumn{1}={}{halign=l},\n}                     %% tabularray inner close\n& Bivariat & Med klasse & Med klasse og utd. \\\\\nKonstant & \\num{99.8} (\\num{0.6}) & \\num{122.6} (\\num{1.5}) & \\num{104.8} (\\num{2.0}) \\\\\nKvinne & \\num{-20.8} (\\num{0.9}) & \\num{-18.2} (\\num{1.0}) & \\num{-17.2} (\\num{1.0}) \\\\\nklasse89II Nedre serviceklasse &  & \\num{-10.4} (\\num{1.7}) & \\num{-4.9} (\\num{1.7}) \\\\\nklasse89III Rutinefunksjonærer &  & \\num{-32.7} (\\num{1.8}) & \\num{-20.4} (\\num{2.0}) \\\\\nklasse89V-VI Faglærte arbeidere &  & \\num{-32.6} (\\num{1.8}) & \\num{-19.7} (\\num{2.0}) \\\\\nklasse89VIIa Ufaglærte arbeidere &  & \\num{-34.0} (\\num{1.8}) & \\num{-19.2} (\\num{2.1}) \\\\\ned &  &  & \\num{2.8} (\\num{0.2}) \\\\\nNum.Obs. & \\num{3759} & \\num{3680} & \\num{3680} \\\\\nR2 & \\num{0.117} & \\num{0.280} & \\num{0.312} \\\\\nF & \\num{496.278} &  &  \\\\\n\\end{tblr}\n\\end{table}\n:::\n:::\n\n\nI den bivariate modellen (modell 1) ser vi den totale lønnsforskjellen mellom menn og kvinner. I modell 2 har vi kontrollert for klasse, og forskjellen er noe redusert. I modell 3 har vi i tillegg kontrollert for utdanning.\n\nLegg merke til to ting: For det første, koeffisienten for `female` endres mellom modellene. For det andre, $R^2$ (forklart varians) øker når vi legger til flere variable. Det betyr at modellen passer bedre til dataene. Men det betyr *ikke* nødvendigvis at modellen er bedre for det vi er interessert i.\n\n\n## Når skal vi kontrollere -- og når skal vi la være?\nDet er fristende å tenke at man bør kontrollere for *alt* man har tilgang til. Men det er ikke riktig. Hvorvidt du bør kontrollere for en variabel avhenger av hva rollen til variabelen er i den sammenhengen du studerer.\n\nEn nyttig tommelfingerregel er at du bør kontrollere for variable som:\n\n1. Påvirker *både* forklaringsvariabelen og utfallsvariabelen (konfunderende variable)\n2. Ikke selv er et *resultat* av forklaringsvariabelen\n\nPunkt 2 er viktig og leder oss til det som kalles *bad controls*.\n\n\n## \"Bad controls\": Ikke kontroller for konsekvenser\nEn vanlig feil er å kontrollere for variable som er *konsekvenser* av den forklaringsvariabelen du er interessert i. Tenk deg at du studerer effekten av utdanning på inntekt. Hvis du kontrollerer for *yrke*, kan du faktisk fjerne en viktig del av effekten -- fordi utdanning påvirker inntekt delvis *gjennom* hvilket yrke man får. Ved å kontrollere for yrke fjerner du denne mekanismen fra estimatet.\n\nTilsvarende: Hvis du er interessert i effekten av kjønn på lønn, bør du tenke nøye gjennom om du skal kontrollere for variabler som arbeidstid eller stillingsnivå. Hvis kvinner systematisk styres mot lavere stillinger *på grunn av* kjønn, er stillingsnivå en *konsekvens* av kjønn -- og da fjerner du en del av den faktiske kjønnseffekten ved å kontrollere for det.\n\nDet finnes ingen enkel mekanisk regel for dette. Du må tenke gjennom *rekkefølgen* av variablene: Hva kommer først? Hva påvirker hva? Et nyttig verktøy for å tenke gjennom dette er såkalte DAGs (Directed Acyclic Graphs), men det går vi ikke inn på her.^[DAGs er et tema som dekkes grundigere i videregående metodekurs.]\n\n\n## Steg-for-steg: Bygge modeller i R\nI praksis vil du ofte bygge opp modeller steg for steg. Her er en oppsummering av fremgangsmåten:\n\n**Steg 1:** Start med den bivariate sammenhengen du er interessert i.\n\n::: {.cell}\n\n```{.r .cell-code}\nmod1 <- lm(time89 ~ female, data = abu89)\n```\n:::\n\n\n**Steg 2:** Legg til variable du mener er konfunderende (bakenforliggende).\n\n::: {.cell}\n\n```{.r .cell-code}\nmod2 <- lm(time89 ~ female + klasse89, data = abu89)\n```\n:::\n\n\n**Steg 3:** Legg eventuelt til ytterligere kontrollvariable.\n\n::: {.cell}\n\n```{.r .cell-code}\nmod3 <- lm(time89 ~ female + klasse89 + ed, data = abu89)\n```\n:::\n\n\n**Steg 4:** Sammenlign modellene i en tabell.\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(list(\"Modell 1\" = mod1,\n                  \"Modell 2\" = mod2,\n                  \"Modell 3\" = mod3),\n             fmt = 1,\n             estimate = \"{estimate} ({std.error})\",\n             statistic = NULL,\n             gof_omit = 'DF|Deviance|R2 Adj.|AIC|BIC|Log.Lik.|RMSE')\n```\n:::\n\n\nDet viktige er ikke bare *tallene*, men *hvordan* koeffisienten du er interessert i endrer seg fra modell til modell. Hvis den endres mye, tyder det på at de variablene du la til er viktige konfunderende variable. Hvis den knapt endrer seg, betyr det at disse variablene ikke forklarer mye av den opprinnelige sammenhengen.\n\n\n## Oppsummering\n- Simpsons paradoks viser at sammenhenger kan snu når man kontrollerer for en tredje variabel.\n- Å \"kontrollere for\" betyr å sammenligne grupper som er like på kontrollvariabelen.\n- Multippel regresjon gjør dette for oss: koeffisienten uttrykker sammenhengen *gitt at de andre variablene holdes konstant*.\n- Du bør kontrollere for variable som påvirker både forklaringsvariabel og utfall (konfunderende variable).\n- Du bør *ikke* kontrollere for variable som er konsekvenser av forklaringsvariabelen (\"bad controls\").\n- Bygg modeller steg for steg og sammenlign med `modelsummary()` for å se hva kontrollvariablene gjør med estimatene.\n",
    "supporting": [
      "kontrollere_for_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularray\"]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"\\\\usepackage[normalem]{ulem}\",\"\\\\usepackage{graphicx}\",\"\\\\usepackage{rotating}\",\"\\\\UseTblrLibrary{siunitx}\",\"\\\\NewTableCommand{\\\\tinytableDefineColor}[3]{\\\\definecolor{#1}{#2}{#3}}\",\"\\\\newcommand{\\\\tinytableTabularrayUnderline}[1]{\\\\underline{#1}}\",\"\\\\newcommand{\\\\tinytableTabularrayStrikeout}[1]{\\\\sout{#1}}\"]}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}