{
  "hash": "a6f8e8ca37960c8a33fe88b483026f37",
  "result": {
    "engine": "knitr",
    "markdown": "# Deskriptive tabeller \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(gtsummary)\n```\n:::\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\nDet kan være ulike grunner til å lage deskriptiv statistikk, og hva du skal bruke tabellene til kan ha betydning for hvordan du lager dem. Noen ganger skal du bare sjekke noen tall, og da er det ingen grunn til å bruke tid på å gjøre tabellen spesiell pen. Andre ganger skal tabellen publiseres i en rapport, på en nettside eller i en vitenskapelig artikkel - eller mest aktuelt på kort sikt: i en masteroppgave. Da må tabellene se ordentlige ut. Nedenfor skal vi se på begge mulighetene. \n\n\n## Quick-and-dirty oppsummeringer \n\nFørst og fremst har vi funksjonen `summary()`. Når denne brukes på et objekt vil hva slags output du får avhenge av objekttypen. Derfor vil `summary()` gi forskjellig output om det er en vektor, et datasett eller et regresjonsobjekt etc. Vi avgrenser oss til datasett her. \n\nHer er output for hele datasettet. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(abu89)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     io_nr          time89             ed             age       \n Min.   :   3   Min.   : 25.00   Min.   : 0.00   Min.   :16.00  \n 1st Qu.:1542   1st Qu.: 71.00   1st Qu.: 1.00   1st Qu.:30.00  \n Median :3093   Median : 83.33   Median : 3.00   Median :39.00  \n Mean   :3105   Mean   : 90.15   Mean   : 2.69   Mean   :39.65  \n 3rd Qu.:4644   3rd Qu.:102.56   3rd Qu.: 3.00   3rd Qu.:48.00  \n Max.   :6258   Max.   :343.75   Max.   :11.00   Max.   :74.00  \n                NA's   :368                                     \n     female                           klasse89    promot          fexp       \n Min.   :0.0000   I Øvre serviceklasse    : 328   NEI:2568   Min.   :0.0000  \n 1st Qu.:0.0000   II Nedre serviceklasse  :1181   JA :1559   1st Qu.:0.2000  \n Median :0.0000   III Rutinefunksjonærer  :1248              Median :0.7000  \n Mean   :0.4686   V-VI Faglærte arbeidere : 648              Mean   :0.9451  \n 3rd Qu.:1.0000   VIIa Ufaglærte arbeidere: 637              3rd Qu.:1.4000  \n Max.   :1.0000   NA's                    :  85              Max.   :4.9000  \n                                                                             \n    private    \n Public :1602  \n Private:2525  \n               \n               \n               \n               \n               \n```\n\n\n:::\n:::\n\nMerk at `summary()` rapporterer forskjellig basert på om variabelen er kontinuerlig eller kategorisk. For kontinuerlige variable gis min/max, kvartiler, median og gjennomsnitt. For kategoriske variable gis det antall i hver kategori. Hvis det er manglende verdier på en variabel står det oppført nederst som antall `NA's`. \n\nMerk her at variabelen female er definert som kontinuerlig selv om det bare er to verdier. Det ville være mer hensiktsmessig å gjøre om denne variabelen til kategorisk. \n\n\nMan kan også bruke `summary()` på enkeltvariable med bruk av `$` som følger: \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(abu89$time89)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  25.00   71.00   83.33   90.15  102.56  343.75     368 \n```\n\n\n:::\n:::\n\nDa får man altså bare tallene for den variabelen man har angitt etter dollartegnet. \n\n\n### Enkeltfunksjoner\nMan kan hente ut hvert av disse tallene spesifikt fremfor å bruke `summary()`. Det er egne funksjoner for dette, og de kan også brukes når man gjør databearbeiding for litt andre formål. Vi ser her på de viktigste. \n\n\nHva om man vil ha en kvartil som ikke er oppgitt i forvalget? Da kan man bruke funksjonen `quantile()`. Argumentene i denne funksjonen er hvilken variabel og hvilket prosentil. Som vi ovenfor inneholder time89 noen NA. Vi må i tillegg bestemme hva vi ønsker å gjøre med NA i beregningen, og vi vil her se bort fra disse ved å angi `na.rm = TRUE`. Ellers får man feilmelding. \n\nHer er eksempel med første kvartil som skal gi samme svar som ovenfor: \n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(abu89$time89, .25, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n25% \n 71 \n```\n\n\n:::\n:::\n\nHer er en variant der man ber om 95-prosentilen: \n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(abu89$time89, .95, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     95% \n148.0362 \n```\n\n\n:::\n:::\n\n\nMan kan også be om flere prosentiler. Da listes disse opp innenfor en `c()` som følger. Her gis prosentilene for 5, 10, 90 og 95 prosent. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(abu89$time89, c(.05, .10, .90, .95), na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       5%       10%       90%       95% \n 54.91651  61.00000 127.77778 148.03618 \n```\n\n\n:::\n:::\n\nGjennomsnittet av en variabel gis ved funksjonen `mean()`: \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(abu89$time89, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 90.14948\n```\n\n\n:::\n:::\n\nStandardavviket gis ved `sd()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(abu89$time89, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 30.31473\n```\n\n\n:::\n:::\n\n\nMedianen kan angis med `quantile()`, men enklere med `median()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedian(abu89$time89, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 83.33333\n```\n\n\n:::\n:::\n\n\n\nVi trenger også ofte antall. `nrow()` gir antall rader, dvs. antall observasjoner i datasettet\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(abu89)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4127\n```\n\n\n:::\n:::\n\n\nTilsvarende gir `ncol()` antall kolonner, mens `dim()` gir begge deler:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nncol(abu89)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(abu89)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4127    9\n```\n\n\n:::\n:::\n\n\n\n## Professjonelle tabeller med gtsummary \nFor å lage ordentlig professjonelle tabeller kreves det mer. For det første skal de se ordentlige ut, men de skal også kunne eksporteres til andre formater på en hensiktsmessig måte. \n\nI R finnes det en hel rekke slike funksjoner. Her har vi vektlagt pakken `gtsummary` fordi den gir gode tabeller fra helt enkle til ganske avanserte relativt lett. Det er også mange muligheter for å justere tabellene slik du vil. Dessuten kan resultatene eksporteres lett til de fleste aktuelle formater (Word, html, pdf, Excel, latex). \n\nAvanserte brukere vil muligens se begrensningene i denne pakken og foretrekke noe annet. De fleste vil kunne lage det aller meste med denne pakken. \n\nVi starter med en enkel oversiktstabell med alle variablene i datasettet. Men vi fjerner løpenummeret for person, nemlig variabelen *io_nr* fordi den ikke inneholder noe analyserbar informasjon.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nabu89 %>% \n  select(-io_nr) %>% \n  tbl_summary()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lc}\n\\toprule\n\\textbf{Characteristic} & \\textbf{N = 4,127}\\textsuperscript{\\textit{1}} \\\\ \n\\midrule\\addlinespace[2.5pt]\nGjennomsnittlig timelønn 1989 & 83 (71, 103) \\\\ \n    Unknown & 368 \\\\ \nÅr utdanning &  \\\\ \n    0 & 839 (20\\%) \\\\ \n    1 & 1,156 (28\\%) \\\\ \n    3 & 1,121 (27\\%) \\\\ \n    5 & 483 (12\\%) \\\\ \n    7 & 308 (7.5\\%) \\\\ \n    9 & 205 (5.0\\%) \\\\ \n    11 & 15 (0.4\\%) \\\\ \nAlder & 39 (30, 48) \\\\ \nRespondentens kjønn & 1,934 (47\\%) \\\\ \nGoldthorpe klasse 1989 &  \\\\ \n    I Øvre serviceklasse & 328 (8.1\\%) \\\\ \n    II Nedre serviceklasse & 1,181 (29\\%) \\\\ \n    III Rutinefunksjonærer & 1,248 (31\\%) \\\\ \n    V-VI Faglærte arbeidere & 648 (16\\%) \\\\ \n    VIIa Ufaglærte arbeidere & 637 (16\\%) \\\\ \n    Unknown & 85 \\\\ \nNoen gang forfremmet &  \\\\ \n    NEI & 2,568 (62\\%) \\\\ \n    JA & 1,559 (38\\%) \\\\ \nBedriftserfaring & 0.70 (0.20, 1.40) \\\\ \nPrivat sektor &  \\\\ \n    Public & 1,602 (39\\%) \\\\ \n    Private & 2,525 (61\\%) \\\\ \n\\bottomrule\n\\end{tabular*}\n\\begin{minipage}{\\linewidth}\n\\vspace{.05em}\n\\textsuperscript{\\textit{1}} Median (Q1, Q3); n (\\%)\\\\\n\\end{minipage}\n\\end{table}\n\n:::\n:::\n\n\nLegg merke til at `tbl_summary` gjør en del ting automatisk. Først og fremst er bruker den *variabel label* og *factor levels* i sidespalten. Ofte vil ikke variable ha slike labler, og da vil det vises variabelnavnene. Variabelen *kjønn* har ikke angitt factor levels, og variabelen har bare verdiene 0 og 1, og da rapporteres kun den ene kategorien (dvs. verdien 1). Vi kan legge til annen tekst hvis vi ønsker. \n\nDernest er det en forhåndsinnstilling som angir at det for kontinuerlige variable skal rapporteres median og interquartile range (IQR), dvs. nedre og øvre kvartil i parentes. Det gir en god beskrivelse av variablene, men vi skal endre dette nedenfor. For kategoriske variable rapporteres det antall observasjoner og andelen i prosent i parentes. \n\nMen merk at for antall år utdanning og kjønn, så er det rapportert som kategoriske variable selv om variabeltypen er kontinuerlig. `tbl_summary` gjør dette fordi det er relativt få kategorier slik at median og IQR ikke er så interessant uansett. \n\n\n\n\nLa oss først endre slik at det rapporteres gjennomsnitt og standardavvik i stedet. Det er mer vanlig å gjøre selv om det ikke er noen regel for dette. Funksjonen `theme_gtsummary_mean_sd()` endrer standardvalget for `tbl_summary` i *alle etterfølgende tabeller*. Dermed slipper du endre neste gang. Flere themes finner du på [pakkens hjemmeside](https://www.danieldsjoberg.com/gtsummary/articles/themes.html). For å gå tilbake til opprinnelig theme brukes funksjonen `reset_gtsummary_theme()`. \n\nVi kan endre andre ting ved tabellen med noen enkle grep. Alle variable kan endre navn i forspalten med å legge til argumentet `label = `. Nedenfor er to variable endret for å vise hvordan man endrer flere variable. Når det er flere variable må de spesifiseres innenfor argumentet `list()` som nedenfor. Her endrer vi også label for variabelen female og klasse89. \n\nNoen ganger kan man også ønske å endre hvordan en variabel presenteres. Et vanlig behov er å presisere hvilken type en variabel er. I dette tilfellet er utdanning antall år etter obligatorisk skolenivå, så det er egentlig en kontinuerlig variabel selv om antall verdier er få. Vi kan velge å presisere at denne er av typen *continuous*. Nedenfor presiserer vi også at female er kategorisk, *dichotomous*, selv om denne ble presentert riktig uansett. Vi bruker argumentet `type = ` og flere variable må oppgis innenfor `list()`. \n\nEn siste ting vi kan endre er å ikke rapportere NA. Det er ikke oppgitt timelønn for alle, så antall NA er rapportert for seg. Det kan være fint, men kan også hende vi ikke ønsker det. Nedenfor er det derfor også lagt til `missing = \"no\"`. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheme_gtsummary_mean_sd()\nabu89 %>% \n  select(-io_nr) %>% \n  tbl_summary(label = list(female ~ \"Kjønn\", klasse89 = \"Klasse\"), \n              type = list(ed ~ \"continuous\", female ~ \"dichotomous\"), \n              missing = \"no\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lc}\n\\toprule\n\\textbf{Characteristic} & \\textbf{N = 4,127}\\textsuperscript{\\textit{1}} \\\\ \n\\midrule\\addlinespace[2.5pt]\nGjennomsnittlig timelønn 1989 & 90 (30) \\\\ \nÅr utdanning & 2.69 (2.56) \\\\ \nAlder & 40 (12) \\\\ \nKjønn & 1,934 (47\\%) \\\\ \nKlasse &  \\\\ \n    I Øvre serviceklasse & 328 (8.1\\%) \\\\ \n    II Nedre serviceklasse & 1,181 (29\\%) \\\\ \n    III Rutinefunksjonærer & 1,248 (31\\%) \\\\ \n    V-VI Faglærte arbeidere & 648 (16\\%) \\\\ \n    VIIa Ufaglærte arbeidere & 637 (16\\%) \\\\ \nNoen gang forfremmet &  \\\\ \n    NEI & 2,568 (62\\%) \\\\ \n    JA & 1,559 (38\\%) \\\\ \nBedriftserfaring & 0.95 (0.91) \\\\ \nPrivat sektor &  \\\\ \n    Public & 1,602 (39\\%) \\\\ \n    Private & 2,525 (61\\%) \\\\ \n\\bottomrule\n\\end{tabular*}\n\\begin{minipage}{\\linewidth}\n\\vspace{.05em}\n\\textsuperscript{\\textit{1}} Mean (SD); n (\\%)\\\\\n\\end{minipage}\n\\end{table}\n\n:::\n:::\n\n\nOfte vil vi ha en tabell som ikke bare viser univariat fordeling, men bi-variate, altså fordelt på to eller flere grupper. Det er f.eks. ganske vanlig å vise tabeller fordelt på kjønn. Det kan vi også gjøre her ved å legge til argumentet `by = female`. Nedenfor er det også forenklet argumentene for `label = ` og `type = `. I slike tilfeller vil vi ofte ha totalen i tillegg til per gruppe, og det gjør vi ved å legge til funksjonen `add_overall()`. \n\nFor de kontinuerlige variablene får vi ikke antallet som inngår i beregningene. Vi vil gjerne vise antall ikke-missing verdier - særlig fordi vi tok vekk NA som egen rad ovenfor. Dette gjør vi ved å legge til funksjonen `add_n()`.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nabu89 %>% \n  select(-io_nr) %>% \n  mutate(female = ifelse(female == 0, \"Menn\", \"Kvinner\")) %>% \n    tbl_summary(by = female, \n                label = list(klasse89 = \"Klasse\"), \n              type = list(ed ~ \"continuous\"), \n              missing = \"no\") %>% \n  add_overall() %>% \n  add_n()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lcccc}\n\\toprule\n\\textbf{Characteristic} & \\textbf{N} & \\textbf{Overall}  N = 4,127\\textsuperscript{\\textit{1}} & \\textbf{Kvinner}  N = 1,934\\textsuperscript{\\textit{1}} & \\textbf{Menn}  N = 2,193\\textsuperscript{\\textit{1}} \\\\ \n\\midrule\\addlinespace[2.5pt]\nGjennomsnittlig timelønn 1989 & 3,759 & 90 (30) & 79 (24) & 100 (32) \\\\ \nÅr utdanning & 4,127 & 2.69 (2.56) & 2.38 (2.40) & 2.96 (2.66) \\\\ \nAlder & 4,127 & 40 (12) & 40 (13) & 40 (12) \\\\ \nKlasse & 4,042 &  &  &  \\\\ \n    I Øvre serviceklasse &  & 328 (8.1\\%) & 74 (3.9\\%) & 254 (12\\%) \\\\ \n    II Nedre serviceklasse &  & 1,181 (29\\%) & 555 (29\\%) & 626 (29\\%) \\\\ \n    III Rutinefunksjonærer &  & 1,248 (31\\%) & 986 (52\\%) & 262 (12\\%) \\\\ \n    V-VI Faglærte arbeidere &  & 648 (16\\%) & 46 (2.4\\%) & 602 (28\\%) \\\\ \n    VIIa Ufaglærte arbeidere &  & 637 (16\\%) & 244 (13\\%) & 393 (18\\%) \\\\ \nNoen gang forfremmet & 4,127 &  &  &  \\\\ \n    NEI &  & 2,568 (62\\%) & 1,308 (68\\%) & 1,260 (57\\%) \\\\ \n    JA &  & 1,559 (38\\%) & 626 (32\\%) & 933 (43\\%) \\\\ \nBedriftserfaring & 4,127 & 0.95 (0.91) & 0.83 (0.81) & 1.05 (0.97) \\\\ \nPrivat sektor & 4,127 &  &  &  \\\\ \n    Public &  & 1,602 (39\\%) & 1,016 (53\\%) & 586 (27\\%) \\\\ \n    Private &  & 2,525 (61\\%) & 918 (47\\%) & 1,607 (73\\%) \\\\ \n\\bottomrule\n\\end{tabular*}\n\\begin{minipage}{\\linewidth}\n\\vspace{.05em}\n\\textsuperscript{\\textit{1}} Mean (SD); n (\\%)\\\\\n\\end{minipage}\n\\end{table}\n\n:::\n:::\n\n\n\nMen vi kan lage mer kompliserte tabeller også. La oss si at vi ønsker å lage den samme tabellen som over, men fordelt på to grupper. Det kan være relevant å sammenligne offentlig og privat sektor. En mulighet er å lage en ny grupperingsvariabel ved å slå sammen kjønn og sektor slik at vi får fire kategorier. Men vi får et bedre resultat ved å lage en stratifisert tabell med funksjonen `tbl_strata()`. Det er litt kryptisk syntaks, men det viktige er å angi hvilken variabel det skal stratifiseres etter med argumentet `strata = ` etterfulgt av `.tbl_fun = ~ .x %>%`, så kommer `tble_summary` etter dette.  Her er det også lagt til en ekstra header med antall observasjoner. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nabu89 %>% \n  select(-io_nr) %>% \n  mutate(female = ifelse(female == 0, \"Menn\", \"Kvinner\")) %>% \n  tbl_strata(strata = private, \n             .tbl_fun = \n               ~ .x %>%\n               tbl_summary(by = female, \n              label = list(klasse89 = \"Klasse\"), \n              type = list(ed ~ \"continuous\"), \n              missing = \"no\") %>%\n               add_n(),\n    .header = \"**{strata}**, N = {n}\"\n    )\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lcccccc}\n\\toprule\n & \\multicolumn{3}{c}{\\textbf{Public}, N = 1602} & \\multicolumn{3}{c}{\\textbf{Private}, N = 2525} \\\\ \n\\cmidrule(lr){2-4} \\cmidrule(lr){5-7}\n\\textbf{Characteristic} & \\textbf{N} & \\textbf{Kvinner}  N = 1,016\\textsuperscript{\\textit{1}} & \\textbf{Menn}  N = 586\\textsuperscript{\\textit{1}} & \\textbf{N} & \\textbf{Kvinner}  N = 918\\textsuperscript{\\textit{1}} & \\textbf{Menn}  N = 1,607\\textsuperscript{\\textit{1}} \\\\ \n\\midrule\\addlinespace[2.5pt]\nGjennomsnittlig timelønn 1989 & 1,403 & 82 (23) & 100 (28) & 2,356 & 76 (24) & 100 (33) \\\\ \nÅr utdanning & 1,602 & 2.88 (2.67) & 4.22 (3.12) & 2,525 & 1.82 (1.92) & 2.50 (2.31) \\\\ \nAlder & 1,602 & 42 (12) & 43 (11) & 2,525 & 37 (13) & 39 (12) \\\\ \nKlasse & 1,592 &  &  & 2,450 &  &  \\\\ \n    I Øvre serviceklasse &  & 55 (5.4\\%) & 150 (26\\%) &  & 19 (2.1\\%) & 104 (6.7\\%) \\\\ \n    II Nedre serviceklasse &  & 340 (34\\%) & 196 (34\\%) &  & 215 (24\\%) & 430 (28\\%) \\\\ \n    III Rutinefunksjonærer &  & 507 (50\\%) & 64 (11\\%) &  & 479 (54\\%) & 198 (13\\%) \\\\ \n    V-VI Faglærte arbeidere &  & 5 (0.5\\%) & 114 (20\\%) &  & 41 (4.6\\%) & 488 (31\\%) \\\\ \n    VIIa Ufaglærte arbeidere &  & 104 (10\\%) & 57 (9.8\\%) &  & 140 (16\\%) & 336 (22\\%) \\\\ \nNoen gang forfremmet & 1,602 &  &  & 2,525 &  &  \\\\ \n    NEI &  & 696 (69\\%) & 318 (54\\%) &  & 612 (67\\%) & 942 (59\\%) \\\\ \n    JA &  & 320 (31\\%) & 268 (46\\%) &  & 306 (33\\%) & 665 (41\\%) \\\\ \nBedriftserfaring & 1,602 & 0.93 (0.85) & 1.15 (0.94) & 2,525 & 0.72 (0.74) & 1.01 (0.98) \\\\ \n\\bottomrule\n\\end{tabular*}\n\\begin{minipage}{\\linewidth}\n\\vspace{.05em}\n\\textsuperscript{\\textit{1}} Mean (SD); n (\\%)\\\\\n\\end{minipage}\n\\end{table}\n\n:::\n:::\n\n\n\nDet går også an å lage langt mer avanserte tabeller enn dette, og alle deler kan modifiseres. Men vi går ikke inn på dette her. Ved behov finner du instruksjoner på [pakkens hjemmeside](https://www.danieldsjoberg.com/gtsummary/index.html).\n\n### Eksport av tabeller\nDu skal aldri bruke \"klipp og lim\" for å få en tabell over i et tekstbehandlingsprogram. Trikset er å konvertere tabellen til gt-format som har en eksportfunksjon til MS Word. \n\nFørst lagres tabellen i et eget objekt. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nfintabell <- abu89 %>% \n  select(-io_nr) %>% \n  mutate(female = ifelse(female == 0, \"Menn\", \"Kvinner\")) %>% \n  tbl_strata(strata = private, \n             .tbl_fun = \n               ~ .x %>%\n               tbl_summary(by = female, \n              label = list(klasse89 = \"Klasse\"), \n              type = list(ed ~ \"continuous\"), \n              missing = \"no\") %>%\n               add_n(),\n    .header = \"**{strata}**, N = {n}\"\n    )\n```\n:::\n\n\nSå kan tabellen eksporteres til Word, og evt. redigeres videre der hvis det trengs. På dette nivået kan det være mer tidsbesparende å gjøre siste justeringer i Word fremfor å lære alle triks for å lage tabellen fiks ferdig i R. (Skal du lage mange tabeller kan det likevel lønne seg å gjøre mest mulig i R). \n\n\n::: {.cell}\n\n```{.r .cell-code}\nfintabell %>% \n  as_gt() %>% \n  gt::gtsave(filename = \"output/fintabell.docx\")\n```\n:::\n\n\nMerk at eksport til docx-formatet krever at du har en relativt ny installasjon av pakkene {gt} og {gtsummary}. Filhalen \".docx\" innebærer at filen lagres i dette formatet. Tilsvarende kan du lagre i .html, .pdf, .rtf, .png, .tex eller .ltex bare ved å endre filhalen. \n\nEn tilsvarende variant som noen av dere har lært på sosgeo1120 er å bruke `as_flextable` og en tilsvarende eksportfunksjon. Det er selvsagt også helt ok. En tidligere versjon av {gt} kunne som sagt ikke eksportere til Word, så da var {flextable} beste løsning. Men pakken {flextable} har vist seg å være litt trøblete å installere på noen pc'er, så da er det bedre å bruke {gt}. \n\n\n\n\n## Manuelle tabeller\nNoen ganger trenger man å lage ganske spesifikke ting. \n\n### For datasettet totalt \n\n\n### Grupperte statistikker \n\n\n\n\n## Oppgaver\n\nSlå opp i boken [R for data science](https://r4ds.had.co.nz/data-visualisation.html) hvis du står fast eller ikke skjønner hva koden betyr. \n\n::: {#exr-}\nBruk datasettet abu89 og lag de samme tabellene som vist her, gjør noen endringer på kodene for å endre utseendet på tabellene. Det er et mål at du skal forstå hva hver enkelt kommando gjør. \n:::\n\n\n::: {#exr-}\nLast inn datasettet `wagepan` fra pakken `wooldridge` i R. Velg noen variable som du selv tenker kan være informative å se nærmere på. Bruk de samme teknikkene på disse variablene.\n:::\n\n\n\n",
    "supporting": [
      "deskriptive_tabeller_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"unnamed-chunk-13\",\"unnamed-chunk-13\",\"unnamed-chunk-13\",\"unnamed-chunk-13\",\"unnamed-chunk-13\",\"unnamed-chunk-13\",\"unnamed-chunk-13\",\"unnamed-chunk-14\",\"unnamed-chunk-14\",\"unnamed-chunk-14\",\"unnamed-chunk-14\",\"unnamed-chunk-14\",\"unnamed-chunk-14\",\"unnamed-chunk-14\",\"unnamed-chunk-15\",\"unnamed-chunk-15\",\"unnamed-chunk-15\",\"unnamed-chunk-15\",\"unnamed-chunk-15\",\"unnamed-chunk-15\",\"unnamed-chunk-15\",\"unnamed-chunk-16\",\"unnamed-chunk-16\",\"unnamed-chunk-16\",\"unnamed-chunk-16\",\"unnamed-chunk-16\",\"unnamed-chunk-16\",\"unnamed-chunk-16\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}