{
  "hash": "7355d5247d6b9ccfb7a712cab480d717",
  "result": {
    "engine": "knitr",
    "markdown": "# Logistisk regresjon\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(haven)\nlibrary(modelsummary)\n```\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\n\n\nI forrige kapittel om den lineære sannsynlighetsmodellen så vi at man kan bruke vanlig lineær regresjon selv om utfallsvariabelen er binær (0/1). Det fungerer greit i mange sammenhenger, men har noen begrensninger. Den viktigste er at modellen kan gi predikerte sannsynligheter som er under 0 eller over 1, noe som jo ikke gir mening. Logistisk regresjon løser dette problemet.\n\nLogistisk regresjon er den vanligste metoden når utfallsvariabelen er binær, altså har to verdier. I samfunnsvitenskapen brukes det veldig mye: er personen i jobb eller ikke? Stemte personen ved valget eller ikke? Har personen høy eller lav inntekt? Osv.\n\n\n## Lage en binær utfallsvariabel\n\nVi skal bruke et eksempel der vi prøver å predikere hvem som har høy timelønn. Vi lager en ny variabel `hoylonn` som er 1 hvis timelønna er over medianen og 0 ellers.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nabu89 <- abu89 %>%\n  mutate(hoylonn = ifelse(time89 > median(time89, na.rm = TRUE), 1, 0))\n```\n:::\n\n\n\n\n\n\n\n\nLa oss sjekke fordelingen:\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(abu89$hoylonn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   0    1 \n1901 1858 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nOmtrent halvparten har høy lønn, noe som gir mening siden vi delte ved medianen.\n\n\n## Hvorfor ikke bare bruke lineær regresjon?\n\nSom vi så i kapittelet om [lineær sannsynlighetsmodell](lineaer_sannsynlighetsmodell.qmd), kan vi bruke vanlig `lm()` også med binær utfallsvariabel. Koeffisientene tolkes da som endring i sannsynlighet (andel). Problemet oppstår spesielt når vi predikerer: vi kan få verdier under 0 eller over 1. Logistisk regresjon sørger for at predikerte sannsynligheter alltid ligger mellom 0 og 1.\n\n\n## Logit-transformasjonen og odds\n\nIdeen bak logistisk regresjon er å modellere *log-oddsen* i stedet for sannsynligheten direkte. Men hva er egentlig odds?\n\nTenk deg at 80 av 100 personer i en gruppe er i jobb. Da er sannsynligheten 0.80 (80%). Oddsen er forholdet mellom sannsynligheten for å være i jobb og sannsynligheten for å *ikke* være i jobb: $0.80 / 0.20 = 4$. Altså: det er fire ganger så sannsynlig å være i jobb som å ikke være det.\n\nLogistisk regresjon modellerer logaritmen av oddsen (log-odds). Fordelen er at log-odds kan variere fritt fra minus uendelig til pluss uendelig, mens sannsynligheter er begrenset mellom 0 og 1. Matematisk sett gjør dette at modellen alltid gir gyldige sannsynligheter.\n\nDu trenger ikke bekymre deg så mye om den matematiske detaljen her. Det viktigste å huske er:\n\n- Koeffisientene fra logistisk regresjon er på log-odds-skalaen\n- Man kan konvertere til odds-ratio ved å eksponentiere: `exp(koeffisient)`\n- Man kan regne om til sannsynligheter med `predict(..., type = \"response\")`\n\n\n## Estimere logistisk regresjon i R\n\nI R bruker vi `glm()` med argumentet `family = binomial` for å estimere logistisk regresjon. Syntaksen er ellers helt lik `lm()`.\n\nLa oss starte enkelt med kjønn som forklaringsvariabel:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogit1 <- glm(hoylonn ~ female, data = abu89, family = binomial)\nsummary(logit1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = hoylonn ~ female, family = binomial, data = abu89)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  0.66334    0.04717   14.06   <2e-16 ***\nfemale      -1.48581    0.07007  -21.20   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 5210.6  on 3758  degrees of freedom\nResidual deviance: 4728.7  on 3757  degrees of freedom\n  (368 observations deleted due to missingness)\nAIC: 4732.7\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nKoeffisienten for `female` er negativ, som betyr at kvinner har lavere log-odds for å ha høy lønn sammenlignet med menn. Men log-odds er ikke veldig intuitivt, så vi konverterer til odds-ratio.\n\n\n## Tolke koeffisientene: odds-ratio\n\nFor å gjøre koeffisientene mer tolkbare konverterer vi fra log-odds til odds-ratio med `exp()`:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(coef(logit1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      female \n  1.9412628   0.2263188 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nEn odds-ratio på 1 betyr ingen forskjell. Over 1 betyr høyere odds, under 1 betyr lavere odds. Koeffisienten for `female` gir en odds-ratio under 1, som altså betyr at kvinner har lavere odds for høy lønn enn menn.\n\nMan kan også få ut konfidensintervaller for odds-ratioene:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(confint(logit1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                2.5 %   97.5 %\n(Intercept) 1.7706203 2.130296\nfemale      0.1971601 0.259492\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n## Flere forklaringsvariable\n\nLa oss utvide modellen med klasse og alder i tillegg til kjønn:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogit2 <- glm(hoylonn ~ female + klasse89 + age, data = abu89, family = binomial)\nsummary(logit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = hoylonn ~ female + klasse89 + age, family = binomial, \n    data = abu89)\n\nCoefficients:\n                                  Estimate Std. Error z value Pr(>|z|)    \n(Intercept)                       1.806579   0.239652   7.538 4.76e-14 ***\nfemale                           -1.618252   0.093501 -17.307  < 2e-16 ***\nklasse89II Nedre serviceklasse   -0.926952   0.217423  -4.263 2.01e-05 ***\nklasse89III Rutinefunksjonærer   -2.751740   0.217219 -12.668  < 2e-16 ***\nklasse89V-VI Faglærte arbeidere  -2.624620   0.224599 -11.686  < 2e-16 ***\nklasse89VIIa Ufaglærte arbeidere -2.990663   0.225225 -13.279  < 2e-16 ***\nage                               0.025410   0.003199   7.944 1.96e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 5100.9  on 3679  degrees of freedom\nResidual deviance: 3886.2  on 3673  degrees of freedom\n  (447 observations deleted due to missingness)\nAIC: 3900.2\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nTolkningen av koeffisientene er litt annerledes enn i lineær regresjon. Hver koeffisient viser endring i log-odds for utfallet (høy lønn) per enhets endring i forklaringsvariabelen, kontrollert for de andre variablene. La oss se på odds-ratioene:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(coef(logit2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     (Intercept)                           female \n                      6.08958125                       0.19824496 \n  klasse89II Nedre serviceklasse   klasse89III Rutinefunksjonærer \n                      0.39575797                       0.06381675 \n klasse89V-VI Faglærte arbeidere klasse89VIIa Ufaglærte arbeidere \n                      0.07246732                       0.05025410 \n                             age \n                      1.02573524 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nOdds-ratioene tolkes slik: en odds-ratio for `age` på f.eks. 1.02 ville bety at for hvert års økning i alder øker oddsen for høy lønn med 2%, kontrollert for kjønn og klasse.\n\n\n## Predikere sannsynligheter\n\nEn veldig nyttig ting med logistisk regresjon er at vi kan predikere sannsynligheter. Vi bruker `predict()` med `type = \"response\"` for å få sannsynligheter i stedet for log-odds:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyedata <- expand.grid(\n  female = c(0, 1),\n  klasse89 = levels(abu89$klasse89)[1:2],\n  age = c(30, 40, 50)\n)\n\nnyedata$pred_sannsynlighet <- predict(logit2, newdata = nyedata, type = \"response\")\nnyedata\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   female               klasse89 age pred_sannsynlighet\n1       0   I Øvre serviceklasse  30          0.9288310\n2       1   I Øvre serviceklasse  30          0.7212393\n3       0 II Nedre serviceklasse  30          0.8377956\n4       1 II Nedre serviceklasse  30          0.5059160\n5       0   I Øvre serviceklasse  40          0.9439043\n6       1   I Øvre serviceklasse  40          0.7693623\n7       0 II Nedre serviceklasse  40          0.8694397\n8       1 II Nedre serviceklasse  40          0.5689974\n9       0   I Øvre serviceklasse  50          0.9559366\n10      1   I Øvre serviceklasse  50          0.8113507\n11      0 II Nedre serviceklasse  50          0.8956791\n12      1 II Nedre serviceklasse  50          0.6299164\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nNå har vi estimerte sannsynligheter for høy lønn for ulike kombinasjoner av kjønn, klasse og alder. Merk at alle verdier ligger mellom 0 og 1, slik det skal være.\n\n\n## Presentere resultater med `modelsummary()`\n\nVi kan bruke `modelsummary()` for å lage pene tabeller, akkurat som for lineær regresjon. Her viser vi først koeffisienter på log-odds-skalaen:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(list(\"Log-odds\" = logit1, \"Log-odds\" = logit2),\n             fmt = 3,\n             estimate = \"{estimate} ({std.error})\",\n             statistic = NULL,\n             gof_omit = 'DF|Deviance|AIC|BIC|Log.Lik.|F|RMSE')\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tblr}[         %% tabularray outer open\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]},\nhline{2}={1-3}{solid, black, 0.05em},\nhline{9}={1-3}{solid, black, 0.05em},\nhline{1}={1-3}{solid, black, 0.08em},\nhline{10}={1-3}{solid, black, 0.08em},\ncolumn{2-3}={}{halign=c},\ncolumn{1}={}{halign=l},\n}                     %% tabularray inner close\n& Log-odds & Log-odds  \\\\\n(Intercept) & \\num{0.663} (\\num{0.047}) & \\num{1.807} (\\num{0.240}) \\\\\nfemale & \\num{-1.486} (\\num{0.070}) & \\num{-1.618} (\\num{0.094}) \\\\\nklasse89II Nedre serviceklasse &  & \\num{-0.927} (\\num{0.217}) \\\\\nklasse89III Rutinefunksjonærer &  & \\num{-2.752} (\\num{0.217}) \\\\\nklasse89V-VI Faglærte arbeidere &  & \\num{-2.625} (\\num{0.225}) \\\\\nklasse89VIIa Ufaglærte arbeidere &  & \\num{-2.991} (\\num{0.225}) \\\\\nage &  & \\num{0.025} (\\num{0.003}) \\\\\nNum.Obs. & \\num{3759} & \\num{3680} \\\\\n\\end{tblr}\n\\end{table}\n:::\n:::\n\n\n\n\n\n\n\n\nVi kan også vise odds-ratioer ved å bruke `exponentiate = TRUE`:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(list(\"OR\" = logit1, \"OR\" = logit2),\n             exponentiate = TRUE,\n             fmt = 2,\n             estimate = \"{estimate} ({std.error})\",\n             statistic = 'conf.int',\n             gof_omit = 'DF|Deviance|AIC|BIC|Log.Lik.|F|RMSE')\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tblr}[         %% tabularray outer open\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]},\nhline{2}={1-3}{solid, black, 0.05em},\nhline{16}={1-3}{solid, black, 0.05em},\nhline{1}={1-3}{solid, black, 0.08em},\nhline{17}={1-3}{solid, black, 0.08em},\ncolumn{2-3}={}{halign=c},\ncolumn{1}={}{halign=l},\n}                     %% tabularray inner close\n& OR & OR  \\\\\n(Intercept) & \\num{1.94} (\\num{0.09}) & \\num{6.09} (\\num{1.46}) \\\\\n& [\\num{1.77}, \\num{2.13}] & [\\num{3.86}, \\num{9.89}] \\\\\nfemale & \\num{0.23} (\\num{0.02}) & \\num{0.20} (\\num{0.02}) \\\\\n& [\\num{0.20}, \\num{0.26}] & [\\num{0.16}, \\num{0.24}] \\\\\nklasse89II Nedre serviceklasse &  & \\num{0.40} (\\num{0.09}) \\\\\n&  & [\\num{0.25}, \\num{0.60}] \\\\\nklasse89III Rutinefunksjonærer &  & \\num{0.06} (\\num{0.01}) \\\\\n&  & [\\num{0.04}, \\num{0.10}] \\\\\nklasse89V-VI Faglærte arbeidere &  & \\num{0.07} (\\num{0.02}) \\\\\n&  & [\\num{0.05}, \\num{0.11}] \\\\\nklasse89VIIa Ufaglærte arbeidere &  & \\num{0.05} (\\num{0.01}) \\\\\n&  & [\\num{0.03}, \\num{0.08}] \\\\\nage &  & \\num{1.03} (\\num{0.00}) \\\\\n&  & [\\num{1.02}, \\num{1.03}] \\\\\nNum.Obs. & \\num{3759} & \\num{3680} \\\\\n\\end{tblr}\n\\end{table}\n:::\n:::\n\n\n\n\n\n\n\n\nMerk `exponentiate = TRUE` som gjør at koeffisientene vises som odds-ratioer. Det er som regel lurt å rapportere odds-ratioer fordi de er lettere å tolke.\n\nFor å eksportere til Word gjøres det på nøyaktig samme måte som for lineær regresjon, ved å sette `output = \"filnavn.docx\"`.\n\n\n## Modelltilpasning\n\nI lineær regresjon har vi $R^2$ som mål på hvor godt modellen passer til dataene. I logistisk regresjon finnes det ingen perfekt ekvivalent, men det finnes flere varianter av pseudo-$R^2$. Disse kan tolkes omtrent på samme måte: et tall mellom 0 og 1 der høyere verdier betyr bedre tilpasning.\n\nEn annen tilnærming er å se på hvor godt modellen klassifiserer observasjonene. Vi kan sammenligne predikerte verdier med faktiske verdier:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nabu89_pred <- abu89 %>%\n  filter(!is.na(hoylonn), !is.na(klasse89), !is.na(age)) %>%\n  mutate(pred_prob = predict(logit2, type = \"response\"),\n         pred_klasse = ifelse(pred_prob > 0.5, 1, 0))\n\ntable(Faktisk = abu89_pred$hoylonn, Predikert = abu89_pred$pred_klasse)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Predikert\nFaktisk    0    1\n      0 1384  480\n      1  479 1337\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nDenne tabellen kalles en *forvirringsmatrise* (confusion matrix). Diagonalen viser korrekte prediksjoner, mens de andre cellene viser feilklassifiseringer. Andelen korrekte prediksjoner kan regnes ut slik:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(abu89_pred$hoylonn == abu89_pred$pred_klasse, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7394022\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nDette gir oss en enkel indikasjon på hvor godt modellen predikerer. Husk imidlertid at hovedpoenget med logistisk regresjon i samfunnsvitenskap som regel er å forstå sammenhenger mellom variable, ikke nødvendigvis å predikere best mulig.\n\n\n## Oppsummering\n\nLogistisk regresjon brukes når utfallsvariabelen er binær (0/1). De viktigste punktene er:\n\n- Bruk `glm(y ~ x, family = binomial)` for å estimere modellen\n- Koeffisientene er på log-odds-skalaen, konverter til odds-ratio med `exp()`\n- Odds-ratio over 1 betyr høyere odds, under 1 betyr lavere odds\n- Bruk `predict(modell, type = \"response\")` for å få predikerte sannsynligheter\n- Bruk `modelsummary()` med `exponentiate = TRUE` for å vise odds-ratioer i tabeller\n- Tolkningen av kontrollvariable er den samme som i lineær regresjon\n",
    "supporting": [
      "logistisk_regresjon_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularray\"]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"\\\\usepackage[normalem]{ulem}\",\"\\\\usepackage{graphicx}\",\"\\\\usepackage{rotating}\",\"\\\\UseTblrLibrary{siunitx}\",\"\\\\NewTableCommand{\\\\tinytableDefineColor}[3]{\\\\definecolor{#1}{#2}{#3}}\",\"\\\\newcommand{\\\\tinytableTabularrayUnderline}[1]{\\\\underline{#1}}\",\"\\\\newcommand{\\\\tinytableTabularrayStrikeout}[1]{\\\\sout{#1}}\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularray\"]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"\\\\usepackage[normalem]{ulem}\",\"\\\\usepackage{graphicx}\",\"\\\\usepackage{rotating}\",\"\\\\UseTblrLibrary{siunitx}\",\"\\\\NewTableCommand{\\\\tinytableDefineColor}[3]{\\\\definecolor{#1}{#2}{#3}}\",\"\\\\newcommand{\\\\tinytableTabularrayUnderline}[1]{\\\\underline{#1}}\",\"\\\\newcommand{\\\\tinytableTabularrayStrikeout}[1]{\\\\sout{#1}}\"]}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}